<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.imgUrl = '<?php echo $this->getViewFileUrl('Magento_Checkout::images/paymentlogoshorizontal1.png'); ?>';
        window.checkoutUrl = 'https://www.2checkout.com';
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>
    <script>
        require([
            'jquery',
            'domReady!',
            'icheck'
        ], function($) {                
                var existCondition = setInterval(function () {
                    if ($("input[data-type='customCheck']").length) {
                         clearInterval(existCondition);
                         $("input[data-type='customCheck']").each(function() {
                                console.log('load icheck');
                                var jQuerythis = $(this);
                                jQuerythis.iCheck();
                            });
                     }
                 }, 100);
                $(document).on('ifChecked','.icheck', function (event) {
                    $(".checkbox-div-show").toggleClass("element-show");
                });
                $(document).on('ifUnchecked','.icheck', function (event) {
                    $(".checkbox-div-show").toggleClass("element-show");
                });
        });
    </script>
</div>
