<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$LangageHelper = $this->helper('FishPig\WordPress\Helper\LangaugeSelect');
$params = $this->getRequest()->getParams();
$languageSelectedOption = $LangageHelper->getLangaugeSession($params);
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="container sort_blogsection">
    <div class="no-leftnav blog-left">
        <div class="breadcrumbs blog-home">   
            <div class="container">
                <ul class="items">
                    <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                        <?php 
                        $links = $crumbInfo['link'];
                        if ($crumbName == "blog") {
                            if ($languageSelectedOption && $this->getRequest()->getFullActionName() == 'wordpress_post_view') {
                                $links = $links.'?lang='.$languageSelectedOption;
                            }
                        } 
                        ?>
                        <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */ $links ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php echo $this->getChildHtml("top_sort"); ?>
        <?php echo $this->getChildHtml("cat_lang");?>
    </div>
</div>
<?php endif; ?>
