<?php 
$blockObj= $block->getLayout()->createBlock('Tatva\Freesamples\Block\ListProduct');
		
?>
<div class="product-info-block">
    <div class="container">
        <div class="main-wrapper list-detail-consistency clearfix">
            <div class="page-title category-title">
                <h1 class="custom-category-title"><?php echo $blockObj->getconfigValue('freesamples_options/general/h1_title'); ?></h1>
                <?php //echo $this->getChildHtml('free.sample.product');?>
                <div class="category-description"><?php echo $blockObj->getconfigValue('freesamples_options/general/descritption'); ?></div>
            </div>
        </div>
    </div>
</div>
