<!-- Facebook Meta Tags -->
<meta property="og:url" content="<?php echo $block->getBaseUrl(); ?>">
<meta property="og:type" content="website">
<meta property="og:title" content="<?php echo $block->getTitle(); ?>">
<meta property="og:description" content="<?php echo $block->getMetaDescription(); ?>">
<meta property="og:image" content="<?php echo $block->getViewFileUrl('Magento_Cms::images/home-page/perfect-visual-img.webp'); ?>">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="slideteam.net">
<meta property="twitter:url" content="<?php echo $block->getBaseUrl(); ?>">
<meta name="twitter:title" content="<?php echo $block->getTitle(); ?>">
<meta name="twitter:description" content="<?php echo $block->getMetaDescription(); ?>">
<meta name="twitter:image" content="<?php echo $block->getViewFileUrl('Magento_Cms::images/home-page/perfect-visual-img.webp'); ?>">