<div class="fancybox-main-dv">
	<div class="popup-title">
		<h1><?php echo __('Submit Your Project') ?></h1>
	</div>
	<div class="general-timeline-progress">
		<img src="<?php echo $block->geTvieWfileUrl('Tatva_Downloadable::images/product-popup/step-3.png') ?>"/>
	</div>
	<div class="popup-content">
		<div class="second-title">			
		</div>
	   <ul class="final-step">	   		
			<li><img src="<?php echo $block->geTvieWfileUrl('Tatva_Downloadable::images/product-popup/final-flag.png') ?>"/></li>
			<li><span><?php echo __('There we are!') ?></span></li>
	   </ul>	
	</div>	
	<div class="footer-text-final">
		<p><?php echo __("We've received your request and currently reviewing it."); ?></p>
		<p><?php echo __("You'll hear back from us within 24 business hours."); ?></p>
	</div>
</div>