<!-- TrustBox widget - Drop-Down -->
<div class="trustpilot-widget" data-locale="en-US" data-template-id="5418052cfbfb950d88702476" data-businessunit-id="5c88cdf9d8c4bb0001df0960" data-style-height="30px" data-style-width="100%" data-theme="light" data-tags="slideteam">
	<a href="https://www.trustpilot.com/review/slideteam.net" target="_blank" rel="noopener">Trustpilot</a>
</div>
<!-- End TrustBox widget -->