<div class="clearfix">
	<div class="hero-bkg-animated">
		<h1 class="about_toptxt">Professional Resume Templates</h1>

		<div class="book_img"><img src="<?php echo $this->getViewFileUrl('FishPig_WordPress::images/book_img.png'); ?>"></div>
		<p>Edge out the competition with our professional and easily customizable Resume 
		templates.  </p>
		
		<div class="downloadbtn">
			<a href="<?php echo $this->getBaseUrl()."resume-template/"; ?>"><img src="<?php echo $this->getViewFileUrl('FishPig_WordPress::images/download_button.gif'); ?>"></a>		
		</div>
	</div>
</div>