        <div class="container">
            <h2>Create an Immersive Training Experience</h2>
            <div class="training_custom">
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon1.png'); ?>" alt="icon" title="Created by subject matter experts with years of experience to ensure that decks' content is in aligned to the industry needs">
                        </div>
                        <h5>Created by Subject Matter Experts</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon2.png'); ?>" alt="icon" title="Impeccably designed slides with attention-grabbing color palettes and visual elements (icons, images, and infographics)">
                        </div>
                        <h5>Professionally Designed Slides</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon3.png'); ?>" alt="icon" title="Detailed concepts organized in structured sessions to ensure quick and effortless assimilation by the trainees">
                        </div>
                        <h5>Structured Sessions</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon4.png'); ?>" alt="icon" title="Comprehensive curriculum to ensure in-depth coverage of topics in each session">
                        </div>
                        <h5>Comprehensive Curriculum</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon5.png'); ?>" alt="icon" title="Detailed teaching notes to assist the trainer in effective delivery of the sessions">
                        </div>
                        <h5>Detailed Teaching Notes</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon6.png'); ?>" alt="icon" title="Real-life case studies to impart practical knowledge to trainees">
                        </div>
                        <h5>Real-Life Case Studies</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon7.png'); ?>" alt="icon" title="Thought-provoking discussion questions and MCQs at the end of each session to assess the learnings of trainees">
                        </div>
                        <h5>Assessment Questions</h5>
                    </div>
                </div>
                <div class="training_set">
                    <div class="training_set_inner">
                        <div class="training_img">
                            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/edutech/training_icon8.png'); ?>" alt="icon" title="Custom and editable proposal to successfully pitch training the course to prospective clients">
                        </div>
                        <h5>Client Proposal</h5>
                    </div>
                </div>
            </div>
        </div>