<?php 
    $helper = $this->helper('Tatva\Theme\Helper\Header');
    $blockObj= $block->getLayout()->createBlock('Mageplaza\SocialLogin\Block\Popup\Social');
    $vs_store_key = $this->helper('Tatva\Theme\Helper\Header')->getConfig('button/config/text') . '/';
?>
<div class="contact-search clearfix">
    <span class="contact-number">
        <i>
            <img src="<?php echo $this->getViewFileUrl('images/us_flag.png'); ?>" alt="Us Flag">
        </i>
        <a href="tel:<?php echo $helper->getConfig('contact/store_phone/phone'); ?>"><?php echo $helper->getConfig('contact/store_phone/phone'); ?></a>
    </span>

 </div>
  
<?php $login = $helper->isCustomerLoggedIn();?>
<?php if(!$login):?>
<?php  $availableSocials = $blockObj->getAvailableSocials();
if ($blockObj->canShow() && sizeof($availableSocials)):
    ?>
    <div class="social-login-authentication-channel account-social-login">
        <div class="social-block">
            <?php foreach ($availableSocials as $key => $social): ?>
                <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $key ?>-login">
                    <a class="btn btn-block btn-social btn-<?= $blockObj->getBtnKey($key) ?> social-btn"
                       data-url='<?php echo $social['login_url'] ?>'>
                        <?php echo __('Sign in with %1', $social['label']) ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php endif;?>
<script>
require(['jquery','socialProvider'],function($){
    $(document).ready(function(){
        $('.btn-social').on('click',function(){
            var url = $(this).data('url');
            if ((jQuery('[name="productId"]').val() != '' &&
                jQuery('[name="productId"]').val() != 'undefined' &&
                jQuery('[name="productId"]').val() != null)) {
                    window.location.href = url +'?productid='+jQuery('[name="productId"]').val();
            }
            else if ((jQuery('[name="product"]').val() != '' &&
                jQuery('[name="product"]').val() != 'undefined' &&
                jQuery('[name="product"]').val() != null)) {
                    window.location.href = url +'?urlredirect='+document.URL;
            }
            else {
                window.location.href = url;
            } 
        })
    });
});
</script>



