<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>

<div class="block block-blog block-blog-subscribe">
	<div class="block-title">
		<strong><span><?php echo "Subscribe to Blog"; ?></span></strong>
	</div>
	<div class="block-content">
		<form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="blog-subscribe-form" data-hasrequired="<?php /* @escapeNotVerified */ echo __('Enter your e-mail address') ?>">
			<div class="blog-search">
				<input type="text" name="email" id="newsletter" class="input-text required-entry validate-email" placeholder="<?php echo __('Enter your e-mail address') ?>"/>
				<button class="btn-default btn start-here-btn" title="<?php echo __('Subscribe') ?>" type="submit"><span><span><?php echo __('Subscribe') ?></span></span></button>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	require(['jquery','mage/mage'], function($)
	{
		$(window).load(function ()
		{
			var dataForm = $('#blog-subscribe-form');
			dataForm.mage('validation', {});
		});
	});
</script>

<!-- <script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('blog-subscribe-form');
    var newsLatter = new Varien.searchForm('blog-subscribe-form', 'newsletter', '<?php //echo __('Enter your e-mail address') ?>');
    newsLatter.initAutocomplete('<?php //echo $this->helper('catalogsearch')->getSuggestUrl(); ?>', 'search_autocomplete');
//]]>
</script> -->