<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#customer-reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" >
   <div class="rating-summary">
      <i class="fa fa-star-o review_icon"></i><label class="summary-text">Customer Reviews</label>
      <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
      <?php if ($rating) : ?>
         <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
            <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
               <span>
                  <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
               </span>
            </span>
         </div>
      <?php else : ?>
         <div class="rating-result">
            <span style="width:0%">
               <span>
                  <span itemprop="ratingValue">0</span>% of <span itemprop="bestRating">100</span>
               </span>
            </span>
         </div>
      <?php endif; ?>
   </div>
   <div class="summary-label">
      <a class="action view" href="<?= $block->escapeUrl($url) ?>">
         <span itemprop="reviewCount"><?= $block->escapeHtml(($block->getReviewsCount() == NULL ? 0 : $block->getReviewsCount())) ?></span>&nbsp;
         <span><?= $block->escapeHtml(__('Customer Reviews')) ?></span>
      </a>
   </div>
</div>

<div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" >
   <div class="rating-summary">
      <i class="fa fa-star-o review_icon"></i><label class="summary-text">Rate this Product</label>
      <span class="label"><span><?= $block->escapeHtml(__('Rate this Product')) ?>:</span></span>
      <a class="action formanchor" href="<?= $block->escapeUrl($urlForm) ?>">
         <div class="rating-result">
            <span style="width:0%">
               <span>
                  <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
               </span>
            </span>
         </div>
      </a>      
   </div>
   <div class="summary-label">
      <a class="action formanchor add" href="<?= $block->escapeUrl($urlForm) ?>"><?= $block->escapeHtml(__('Rate This Product')) ?></a>
   </div>
</div>