<div class="page-sitemap">
	<div class="main-wrapper clearfix">
		<div class="page-title">
			<h4 class="custom-category-title"><?php echo __('Products'); ?></h4>
		</div>
	</div>	
	<div id="sitemap_top_links">
    	<div class="links">
        	<ul>
            	<li class="first last"><a href="<?php echo __($block->getCategorySitemapUrl('catalog/seo_sitemap/category/')); ?>" title="Category Sitemap">Category Sitemap</a></li>
            </ul>
		</div>
    </div>
	<?php if ($block->getPagerHtml()): ?>
	    <?php echo $block->getPagerHtml(); ?>
	<?php endif ?>
	<?php $products = $block->getProductCollection(); ?>
	<?php if ($products && count($products)): ?>
		<div class="container listing-container">
			<div class="main-wrapper clearfix">
		    	<ul class="sitemap ">
					<?php foreach($products as $product) : ?>
						<li>
							<a href="<?php echo $product->getProductUrl(); ?>" ><?php echo $product->getName(); ?></a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
		<?php if ($block->getPagerHtml()): ?>
			<?php echo $block->getPagerHtml(); ?>
		<?php endif ?>

	<?php else: ?>
	    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
	<?php endif ?>
</div>