<script>
    require([
        'jquery',
        'uiRegistry'
    ], function($,uiRegistry){
        uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_ttoken", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_tid", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_ltoken", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_lid", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_gtoken", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_gid", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_ftoken", function (element) {
         element.hide();
      });  
       uiRegistry.get("customer_form.areas.customer.customer.inchoo_socialconnect_fid", function (element) {
         element.hide();
      });        
    })
</script>