<?php
/**
 * @category   Tatva
 * @package    Tatva_Gtm
 */

/** @var \Tatva\Gtm\Block\Gtminit $block */
$page_type = $block->getRequest()->getFullActionName();

?>

<?php if($page_type == "checkout_onepage_success"): ?>
	<script type="text/javascript">
		var order_success_data = <?php echo $block->getOrderSuccessData();?>;
		dataLayer.push(order_success_data);
		console.log(order_success_data);
	</script>
<?php endif; ?>
<?php if($page_type == "catalog_product_view"): ?>
	<script type="text/javascript">
		var product_layer_data = <?php echo $block->getProductLayerData();?>;
		dataLayer.push(product_layer_data);
		console.log(product_layer_data);
	</script>
<?php endif; ?>