<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php
	$static_content =  $this->getStoreConfigValue()->getValue('button/social_sharing_config/text_field1');
?>
<meta property="og:type" content="product" />
<meta property="og:title" content="<?php echo $static_content;?>" />
<meta property="og:image" content="<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_page_image_large')->getImageUrl()) ?>" />
<meta property="og:image:width" content="960" />
<meta property="og:image:height" content="720" />
<meta property="og:description" content="<?php echo  $static_content;?>" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>" />
<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
    <meta property="product:price:amount" content="<?= /* @escapeNotVerified */ $priceAmount ?>"/>
    <?= $block->getChildHtml('meta.currency') ?>
<?php endif;?>
