<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer_demo">
	<button class="btn btn-black btn-white book_demo" title="Schedule a live product demo" data-mage-init='{"popupWindow": {"windowURL":"https://app.greminders.com/t/d42867b4/slideteam","windowName":"orderitems","width":1500,"height":700,"top":0,"left":0,"resizable":1,"scrollbars":1}}'>Schedule a live product demo</button>
</div>
<small class="copyright">
    <span>Copyright &copy; <?php echo date('Y') ?> SlideTeam. All Rights Reserved.</span>
</small>
