<!-- Google Review in Footer -->
<div id="lcqualitybadge" class="qualitybadge"></div>
<div class="custom-google-review">
	<a href="https://www.google.com/maps/place//data=!4m2!3m1!1s0x89c258f98f2c5ca5:0x86f66552b4ac7a1a?source=g.page.m.we._" rel="noopener" target="_blank" title="Google Reviews">
		<img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/Google_reviewimg.jpg'); ?>" alt="Google Reviews" loading="lazy" />
	</a>
</div>