<?php
$helper = $this->helper('Tatva\Theme\Helper\Header');

$baseUrl = $helper->getBase(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$mediaUrl = $helper->getBase(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<ul id="new-menu">

    <li class="vwo-menu clearfix templates"><a class="menu-item" href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Powerpoint Templates">
        <p style="">Powerpoint Templates</p></a> 
    </li> 

    <li class="vwo-menu clearfix proposals"><a class="menu-item" href="<?php echo $baseUrl ?>one-page-summary-documents.html" title="One Pagers">
        <p style="">One Pagers</p></a> 
    </li>

    <li class="vwo-menu clearfix one-page-summary">
        <a class="menu-item" id="One Page Summary" href="https://www.slideteam.net/ppt-templates/strategy-PowerPoint" title="Strategy">
            <p>Strategy</p>
        </a>
    </li>

    <li class="vwo-menu clearfix management"><a class="menu-item" href="https://www.slideteam.net/ppt-templates/proposal-presentations" title="Proposals">
        <p style="">Proposals</p></a> 
    </li> 

    <li class="vwo-menu clearfix strategy"><a class="menu-item" href="https://www.slideteam.net/ppt-templates/KPI-dashboard" title="Kpi Dashboard">
            <p style="">Kpi Dashboard</p></a>
    </li>

    <li class="vwo-menu clearfix pitch-decks">
        <a class="menu-item" href="https://www.slideteam.net/professional-powerpoint-templates" title="Professional">
            <p style="">Professional</p>
        </a>
    </li>

    <li class="vwo-menu clearfix roadmap"><a class="menu-item" href="https://www.slideteam.net/powerpoint-presentation-slides/roadmap-powerpoint-templates-and-presentation-slides.html" title="Roadmap">
            <p style="">Roadmap</p></a>
    </li>

    <li class="vwo-menu clearfix process"><a class="menu-item" href="https://www.slideteam.net/ppt-templates/management-slides" title="Management">
            <p style="">Management</p></a>
    </li>

    <li class="vwo-menu clearfix KPI-dashboards"><a class="menu-item" href="https://www.slideteam.net/pitch-deck" title="Pitch Deck">
            <p style="">Pitch Deck</p></a>
    </li>

    <li class="vwo-menu clearfix timelines"><a class="menu-item" href="https://www.slideteam.net/powerpoint-templates/background.html" title="Background">
            <p style="">Background</p></a>
    </li>

    <li class="vwo-menu clearfix vision-mission"><a class="menu-item" href="https://www.slideteam.net/ppt-templates/resume-presentations" title="Resume">
            <p style="">Resume</p></a>
    </li>

    <li class="vwo-menu clearfix technology"><a class="menu-item" href="<?php echo $baseUrl ?>powerpoint-images.html" title="Icons">
            <p style="">Icons</p></a>
    </li>

    <li class="vwo-menu clearfix org-chart"><a class="menu-item" href="https://www.slideteam.net/business-plans-powerpoint-templates.html" title="Business Plans">
            <p style="">Business Plans</p></a>
    </li>

    <li class="vwo-menu clearfix icons">
        <a class="menu-item" id="Icons" href="https://www.slideteam.net/ppt-templates/SWOT" title="Swot Analysis">
            <p>Swot Analysis</p>
        </a>
    </li>

    <li class="vwo-menu clearfix background-PPT">
        <a class="menu-item" href="https://www.slideteam.net/project-management-timeline-gantt-chart.html" title="Gantt Chart">
            <p style="">Gantt Chart</p>
        </a>
    </li>

    <li class="vwo-menu clearfix project-management">
        <a class="menu-item" href="https://www.slideteam.net/blog/top-15-animated-powerpoint-templates-to-edit-and-download" title="Animated">
            <p style="">Animated</p>
        </a>
    </li>

    <li class="vwo-menu clearfix children-kids-PPT">
        <a class="menu-item" href="https://www.slideteam.net/example-budget-presentation-powerpoint-presentation-slides.html" title="Budget">
            <p style="">Budget</p>
        </a>
    </li>

    <li class="vwo-menu clearfix professional-PPT">
        <a class="menu-item" href="https://www.slideteam.net/powerpoint-presentation-essentials/agenda-slides.html" title="Agenda">
            <p style="">Agenda</p>
        </a>
    </li>

    <li class="vwo-menu clearfix roadmap-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/flowchart-powerpoint" title="Flowchart">
            <p style="">Flowchart</p>
        </a>
    </li>

    <li class="vwo-menu clearfix timeline-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/proposal-presentations" title="Business Proposal">
            <p style="">Business Proposal</p>
        </a>
    </li>

    <li class="vwo-menu clearfix free-business-PPT">
        <a class="menu-item" href="https://www.slideteam.net/marketing-plan-powerpoint-presentation-slides.html" title="Marketing Plan">
            <p style="">Marketing Plan</p>
        </a>
    </li>

    <li class="vwo-menu clearfix comparison-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Business">
            <p style="">Business</p>
        </a>
    </li>

    <li class="vwo-menu clearfix PPT-presentations">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/marketing-slides" title="Marketing">
            <p style="">Marketing</p>
        </a>
    </li>

    <li class="vwo-menu clearfix business-plan-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/planning-slides" title="Planning">
            <p style="">Planning</p>
        </a>
    </li>


    <li class="vwo-menu clearfix startup-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/org-chart" title="Org Charts">
            <p style="">Org Charts</p>
        </a>
    </li>

    <li class="vwo-menu clearfix team-intro-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/data-powerpoint" title="Data">
            <p style="">Data</p>
        </a>
    </li>

    <li class="vwo-menu clearfix medical-PPT">
        <a class="menu-item" href="https://www.slideteam.net/powerpoint-presentation-essentials/project-management-slides.html" title="Project Management">
            <p style="">Project Management</p>
        </a>
    </li>

    <li class="vwo-menu clearfix company-profile">
        <a class="menu-item" href="https://www.slideteam.net/search/go?&w=education" title="Education">
            <p style="">Education</p>
        </a>
    </li>

    <li class="vwo-menu clearfix product-PPT">
        <a class="menu-item" href="https://www.slideteam.net/complete-powerpoint-decks-presentations/case-study.html" title="Business Case">
            <p style="">Business Case</p>
        </a>
    </li>

    <li class="vwo-menu clearfix agenda-slides-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/sales-presentations" title="Sales">
            <p style="">Sales</p>
        </a>
    </li>

    <li class="vwo-menu clearfix Job-interview-ppt">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Creative">
            <p style="">Creative</p>
        </a>
    </li>

    <li class="vwo-menu clearfix about-me-slides">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Cool">
            <p style="">Cool</p>
        </a>
    </li>

    <li class="vwo-menu clearfix process-flow-PPT">
        <a class="menu-item" href="https://www.slideteam.net/business-model-powerpoint-presentation-slides.html" title="Business Model">
            <p style="">Business Model</p>
        </a>
    </li>

    <li class="vwo-menu clearfix free-PPT">
        <a class="menu-item" href="https://www.slideteam.net/cybersecurity-powerpoint-presentation-slides.html" title="Cyber Security">
            <p style="">Cyber Security</p>
        </a>
    </li>

    <li class="vwo-menu clearfix free-PPT-templates">
        <a class="menu-item" href="https://www.slideteam.net/technology-powerpoint-templates.html" title="Technology">
            <p style="">Technology</p>
        </a>
    </li>

    <li class="vwo-menu clearfix thesis-PPT">
        <a class="menu-item" href="https://www.slideteam.net/powerpoint-presentation-slides/process-powerpoint-templates-and-presentation-slides.html" title="Process">
            <p style="">Process</p>
        </a>
    </li>

    <li class="vwo-menu clearfix christian-church">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/medical-presentations" title="Medical">
            <p style="">Medical</p>
        </a>
    </li>

    <li class="vwo-menu clearfix introduction-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Business PPT">
            <p style="">Business PPT</p>
        </a>
    </li>

    <li class="vwo-menu clearfix budget-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/digital-marketing" title="Digital Marketing">
            <p style="">Digital Marketing</p>
        </a>
    </li>

    <li class="vwo-menu clearfix Artificial-intel-AI">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/finance-presentations" title="Finance">
            <p style="">Finance</p>
        </a>
    </li>

    <li class="vwo-menu clearfix project-powerPoint">
        <a class="menu-item" href="https://www.slideteam.net/startup-business-plan-powerpoint-presentation-slides.html" title="Startup">
            <p style="">Startup</p>
        </a>
    </li>

    <li class="vwo-menu clearfix research-proposal">
        <a class="menu-item" href="https://www.slideteam.net/digital-transformation-powerpoint-presentation-slides.html" title="Digital Transformation">
            <p style="">Digital Transformation</p>
        </a>
    </li>

    <li class="vwo-menu clearfix proposals">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/HR" title="Human Resources">
            <p style="">Human Resources</p>
        </a>
    </li>

    <li class="vwo-menu clearfix sales-presentation">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/product-management" title="Product Management">
            <p style="">Product Management</p>
        </a>
    </li>

    <li class="vwo-menu clearfix project-management">
        <a class="menu-item" href="https://www.slideteam.net/introduction-to-artificial-intelligence-powerpoint-presentation-slides.html" title="Artificial Intelligence">
            <p style="">Artificial Intelligence</p>
        </a>
    </li>

    <li class="vwo-menu clearfix marketing-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/operations-powerpoint" title="Operations">
            <p style="">Operations</p>
        </a>
    </li>

    <li class="vwo-menu clearfix comparison-PPT">
        <a class="menu-item" href="https://www.slideteam.net/company-profile-powerpoint-presentation-slides.html" title="Company Profile">
            <p style="">Company Profile</p>
        </a>
    </li>

    <li class="vwo-menu clearfix leadership-PPT">
        <a class="menu-item" href="https://www.slideteam.net/acknowledgement-for-project-with-gratitude-shown-at-the-end.html" title="Acknowledgement PPT">
            <p style="">Acknowledgement PPT</p>
        </a>
    </li>

    <li class="vwo-menu clearfix executive-summary">
        <a class="menu-item" href="https://www.slideteam.net/complete-powerpoint-decks-presentations.html" title="PPT Presentation">
            <p style="">PPT Presentation</p>
        </a>
    </li>

    <li class="vwo-menu clearfix project-status-PPT">
        <a class="menu-item" href="https://www.slideteam.net/ppt-templates/reports-brochures" title="Reports Brochures">
            <p style="">Reports Brochures</p>
        </a>
    </li>

    <li class="vwo-menu clearfix pitch-deck-PPT">
        <a class="menu-item" href="https://www.slideteam.net/blog/top-10-one-pager-startup-templates" title="One Page Pitch">
            <p style="">One Page Pitch</p>
        </a>
    </li>

    <li class="vwo-menu clearfix templates"><a class="menu-item" href="https://www.slideteam.net/example-presentation-for-job-interview-powerpoint-presentation-slides.html" title="Interview PPT">
        <p style="">Interview PPT</p></a> 
    </li>
    
    <li class="vwo-menu clearfix startup-PPT">
        <a class="menu-item" href="<?php echo $baseUrl ?>all-items" title="All Categories">
            <p style="">All Categories</p>
        </a> 
    </li>
    
</ul>


<script>
    require([
        'jquery'
    ],
    
            function ($) {
                //Objects

                var visitedMenu = false;

                //DOM Changes
                //$('#mega-3').before(contentHtml.menu);

                //Events
                
                //For desktop view
                if($(window).width() > 1023){
                    $('#ppt_templates')
                            .hover(function () {
                                $('#mega-3').show();
                            });

                    $('#ppt_templates').mouseleave(function () {
                        var interval = setTimeout(function () {
                            if (!visitedMenu)
                                $('#mega-3').hide();
                        }, 100);
                    });

                    $('#mega-3').mouseenter(function () {
                        visitedMenu = true;
                    });

                    $('#mega-3').mouseleave(function () {
                        visitedMenu = false;
                        $('#mega-3').hide();
                    });
                }
            });
</script>

