<script type="text/javascript">
    require(['jquery','owl_carausel','Ddimgtooltip'], function ($){ });
</script>
<?php  

$identifier = trim($this->getRequest()->getOriginalPathInfo(), '/');
if(strpos($identifier, 'google-slides') !== false):
                 
$catname = $block->getRegistry()->registry('current_category')->getName(); ?>

<script type="text/html" id="listing-slide<?php echo 1;?>">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-title-top">
        <h4> Recommended For You</h4>
    </div>
    <amfpc name="tatva_emarsys_slides_widget_<?php echo 1;?>">
        <div class="recommended-outer">
          <div id="slides1" class="recommended-list google-slides-list owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ var p = SC.page.products[i];
                    var remaining = p.c_number_of_slides-3;
                    var count_total_images = p.c_number_of_slides;
                    first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
                    first_thumbnail = p.c_thumbnail_1;
                    second_thumbnail = p.c_thumbnail_2;
                    third_thumbnail = p.c_thumbnail_3;
                    fourth_thumbnail = p.c_thumbnail_4;
                    fifth_thumbnail = p.c_thumbnail_5;
                    sixth_thumbnail = p.c_thumbnail_6;
                }}
                <div data-scarabitem="{{= p.id }}" class="item">
                    <a class="product-image image-height" title="{{= p.title }}" href="{{= p.link }}">

                        <img class="small_image_hover" rel='imgtip[{{= p.id }}110000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}" src="{{= p.image }}">
                        {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                                <span class="badge-label">Animated</span>
                        {{ } }}
                    </a>
                    <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                        <p class="product-name name-content-trim"><a rel='imgtip[{{= p.id }}110000]' title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
                    </div>              
                </div>
            {{ } }}
          </div>
        </div>
    </amfpc>
    {{ } }}
    ]]>
</script>

<script type="text/javascript">
  
require(['jquery','Emarsysjs','jQdotdot'], function (jQuery){
  ScarabQueue.push(['searchTerm', '<?php echo $catname; ?>']);
  ScarabQueue.push(['recommend',
  {
    logic: 'SEARCH',
    limit: 30,
    containerId: 'googleslides1',
    templateId: 'listing-slide1',
    success: function(SC, render)
    {
      render(SC);
      jQuery("#slides1").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
          ddimgtooltip.init("*[rel^=imgtip]");
          jQuery('.name-content-trim').dotdotdot(
          {
            callback: function (isTruncated) {},
            ellipsis: "\u2026 ",
            height: 45,
            keep: null,
            tolerance: 0,
            truncate: "word",
            watch: "window",
          })
          jQuery('.description-content-trim').dotdotdot(
          {
            callback: function (isTruncated) {},
            ellipsis: "\u2026 ",
            height: 120,
            keep: null,
            tolerance: 0,
            truncate: "word",
            watch: "window",
          })
    }
  }]);
});
</script>

<?php endif; ?>

