<div class="before_emarsys"></div>
<div id="wordpress-sidebar-term"></div>

<script type="text/html" id="personal-template">
<![CDATA[
{{ if (SC.page.products.length) { }}
<amfpc name="tatva_emarsys_product_widget_personal">
    <div class="verticla-slider-content products-grid-outer blog-vertical-slider">
        <section class="vertical-center slider products-grid">
            {{ for (var i=0; i < SC.page.products.length; i++) { }}
            {{ var p = SC.page.products[i];
             var remaining = p.c_number_of_slides-3;
            var count_total_images = p.c_number_of_slides;
			first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
			first_thumbnail = p.c_thumbnail_1;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
       	}}
            <div data-scarabitem="{{= p.id }}">
                <a class="product-image image-height" title="{{= p.title }}" href="javascript:void(0)">
                    <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}"
                    new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"        
                    src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                    data-src="{{= p.image }}" >
                    /*<img class="small_image_hover" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" src="{{= p.image }}" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/home-page/home_widgets_placeholder.png')?>" >*/
                    <!--<img class="small_image_hover" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= p.image }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" src="{{= p.image }}" >-->
                    {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                        <span class="badge-label">Animated</span>
                    {{ } }}
                </a>
              <div class="product-info name-only">
                <p class="product-name"><a rel='imgtip[{{= p.id }}10000]' title="{{= p.title }}" href="{{= p.link }}">{{= p.title }}</a></p>
              </div> 
            </div>
            {{ } }}
        </section>
    </div>
</amfpc>
{{ } }}
]]>
</script>

<script type="text/javascript">
require(['jquery','Emarsysjs','slick_min'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'PERSONAL',
        containerId: 'wordpress-sidebar-term',
        limit: 15,
        templateId: "personal-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".vertical-center").slick({
                vertical: true,
                slidesToShow: 10,
                initialSlide : 0,
                infinite : false

            });
            ddimgtooltip.init("*[rel^=imgtip]");
        }
    }]);
    //ScarabQueue.push(['go']);
});
</script>

        