<?php $field = "Complete Decks"; ?>
<?php $custom_category = array($field);?>
<?php $i = 1; ?>
<script type="text/html" id="simple-tmpl<?php echo $i;?>">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="main-wrapper">
        <h6 class="currently-trending-title"><span class="border"></span> Currently Trending <span class="border"></span></h6>
        <div id="cat<?php echo $i;?>"class="owl-carousel owl-theme trending-slider">
        {{ for (var i=0; i < SC.page.products.length; i++) { }}
        {{ 
        var p = SC.page.products[i];
        var count_total_images = p.c_number_of_slides;
        var remaining = p.c_number_of_slides-3;
        first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
        first_thumbnail = p.c_thumbnail_1;
        second_thumbnail = p.c_thumbnail_2;
        third_thumbnail = p.c_thumbnail_3;                
        fourth_thumbnail = p.c_thumbnail_4;
        fifth_thumbnail = p.c_thumbnail_5;
        sixth_thumbnail = p.c_thumbnail_6;
            }}
            <div data-scarabitem="{{= p.id }}" class="item" data-id="{{= i }}">
                <a href="{{= p.link }}" title="{{= p.title }}">
                    <img class="lazyload small_image_hover" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" 
                    new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"
                    src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                    data-src="{{= p.image }}">
                    {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                        <span class="badge-label">Animated</span>
                    {{ } }}
                </a>
                <a href="{{= p.link }}" title="{{= p.title }}">
                    <p class='content-trim' rel='imgtip[{{= p.id }}10000]'>{{= p.title }}</p>
                </a>
            </div>
            {{ } }}
        </div>
    </div>
    {{ } }}
    ]]>
</script>
<script type="text/javascript">
    require(['jquery','EmarsysWidgetJs','owl_carausel','jQdotdot','domReady'], function (jQuery){
        
        ScarabQueue.push(['category','<?php echo $field; ?>']);
        ScarabQueue.push(['recommend',
        {
            logic: 'CATEGORY_<?php echo $i;?>',
            limit: 10,
            containerId: 'topic<?php echo $i;?>',
            templateId: 'simple-tmpl<?php echo $i;?>',
            success: function(SC, render)
            {
                
                render(SC);
                jQuery("#cat<?php echo $i;?>").owlCarousel({
                    /*navigation : true,*/
                    nav:true,
                    pagination:false,
                    items : 7,
                    itemsCustom : false,
                    rewindNav : false,
                    lazyLoad: false,
                    slideBy:7,
                    responsiveClass:true,
                    scrollPerPage : true,
                    navText : ["", ""],
                    responsive:{
                        0:{ 
                            items:2
                        },
                        576:{
                            items:3
                        },
                        768:{
                            items:4
                        },
                        992:{
                            items:5
                        },
                        1024:{
                            items:6
                        },
                        1680:{
                            items:7
                        }
                    }
                });
                ddimgtooltip.init("*[rel^=imgtip]");
                /*jQuery('.content-trim').dotdotdot({
                    callback: function (isTruncated) {},
                    ellipsis: "\u2026 ",
                    height: 60,
                    keep: null,
                    tolerance: 0,
                    truncate: "word",
                    watch: "window",
                });*/
            }
        }]);    
    });
</script>
<?php $i = 2; ?>
<script type="text/html" id="simple-tmpl<?php echo $i;?>">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="main-wrapper">
        <h6 class="currently-trending-title"><span class="border"></span> Currently Trending <span class="border"></span></h6>
        <div id="cat<?php echo $i;?>"class="owl-carousel owl-theme trending-slider">
        {{ for (var i=0; i < SC.page.products.length; i++) { }}
        {{ 
        var p = SC.page.products[i];
        var count_total_images = p.c_number_of_slides;
        var remaining = p.c_number_of_slides-3;
        first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
        first_thumbnail = p.c_thumbnail_1;
        second_thumbnail = p.c_thumbnail_2;
        third_thumbnail = p.c_thumbnail_3;                
        fourth_thumbnail = p.c_thumbnail_4;
        fifth_thumbnail = p.c_thumbnail_5;
        sixth_thumbnail = p.c_thumbnail_6;
            }}
            <div data-scarabitem="{{= p.id }}" class="item" data-id="{{= i }}">
                <a href="{{= p.link }}" title="{{= p.title }}">
                    <img class="lazyload small_image_hover" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" 
                    new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"
                    src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                    data-src="{{= p.image }}">
                    {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                        <span class="badge-label">Animated</span>
                    {{ } }}
                </a>
                <a href="{{= p.link }}" title="{{= p.title }}">
                    <p class='content-trim' rel='imgtip[{{= p.id }}10000]'>{{= p.title }}</p>
                </a>
            </div>
            {{ } }}
        </div>
    </div>
    {{ } }}
    ]]>
</script>
<script type="text/javascript">
    require(['jquery','EmarsysWidgetJs','owl_carausel','jQdotdot','domReady'], function (jQuery){
        
        ScarabQueue.push(['recommend',
        {
            logic: 'HOME_<?php echo $i;?>',
            limit: 10,
            containerId: 'topic<?php echo $i;?>',
            templateId: 'simple-tmpl<?php echo $i;?>',
            success: function(SC, render)
            {
                
                render(SC);
                jQuery("#cat<?php echo $i;?>").owlCarousel({
                    /*navigation : true,*/
                    nav:true,
                    pagination:false,
                    items : 7,
                    itemsCustom : false,
                    rewindNav : false,
                    lazyLoad: false,
                    slideBy:7,
                    responsiveClass:true,
                    scrollPerPage : true,
                    navText : ["", ""],
                    responsive:{
                        0:{ 
                            items:2
                        },
                        576:{
                            items:3
                        },
                        768:{
                            items:4
                        },
                        992:{
                            items:5
                        },
                        1024:{
                            items:6
                        },
                        1680:{
                            items:7
                        }
                    }
                });
                ddimgtooltip.init("*[rel^=imgtip]");
                /*jQuery('.content-trim').dotdotdot({
                    callback: function (isTruncated) {},
                    ellipsis: "\u2026 ",
                    height: 60,
                    keep: null,
                    tolerance: 0,
                    truncate: "word",
                    watch: "window",
                });*/
            }
        }]);
    });
</script>