<div class="one-page-slider onepg-sub-cls">
    <div id="ppage-topic1"></div>
    <div id="ppage-topic2"></div>
    <div id="ppage-topic3"></div>
    <div id="ppage-topic4"></div>
</div>
<?php $fullPath = $block->getRequest()->getFullActionName(); ?>
<?php if($fullPath!="subscription_index_list"):?>
    <?php if($block->getRegistry()->registry('current_product')):
        $product_data = $block->getRegistry()->registry('current_product')->getData(); ?>
<?php endif; ?>

<script type="text/html" id="category-template">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Related one-page document</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_related">
        <div class="recommended-outer">
            <div class="recommended-list related owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ 
            var p = SC.page.products[i];
            var count_total_images = p.c_number_of_slides;
            var remaining = p.c_number_of_slides-3;
            first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
            first_thumbnail = p.zoom_image;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;                
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
            thumbimg = p.c_spl_thumbnail;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="" zoomsrc3=""
                src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                data-src="{{= thumbimg }}" custompage="1">
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>
<script type="text/javascript">
    ScarabQueue.push(['category','Letterheads']);
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'CATEGORY_0',
        limit: 15,
        containerId: 'ppage-topic1',
        templateId: "category-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    450:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    630:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    930:{
                        items:5,
                        slideBy:5,
                        nav:true
                    },
                    1367:{
                        items:6,
                        slideBy:6,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>

<script type="text/html" id="related-template">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Related Products</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_related">
        <div class="recommended-outer">
            <div class="recommended-list related owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ 
            var p = SC.page.products[i];
            var count_total_images = p.c_number_of_slides;
            var remaining = p.c_number_of_slides-3;
            first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
            first_thumbnail = p.c_thumbnail_1;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;                
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" 
                new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"
                src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                data-src="{{= p.image }}" >
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>

<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED',
        containerId: 'ppage-topic2',
        limit: 15,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>

<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED_2',
        containerId: 'ppage-topic4',
        limit: 15,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>

<script type="text/html" id="category-template-second">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Related one-page document</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_related">
        <div class="recommended-outer">
            <div class="recommended-list second-category owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ 
            var p = SC.page.products[i];
            var count_total_images = p.c_number_of_slides;
            var remaining = p.c_number_of_slides-3;
            first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
            first_thumbnail = p.zoom_image;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;                
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
            thumbimg = p.c_spl_thumbnail;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="" zoomsrc3="" src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                data-src="{{= thumbimg }}" custompage="1">
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>
<script type="text/javascript">
    ScarabQueue.push(['category','Letterheads']);
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'CATEGORY_1',
        limit: 12,
        containerId: 'ppage-topic3',
        templateId: "category-template-second",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".second-category").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    450:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    630:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    930:{
                        items:5,
                        slideBy:5,
                        nav:true
                    },
                    1367:{
                        items:6,
                        slideBy:6,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>
<?php endif; ?>