<?php if($this->getEmarsysIntegrationStatus()):?>
    <div id="related-recs"></div>
    <div id="related-recs2"></div>
    <div id="related-recs3"></div>
    <div id="bought-recs"></div>
    <div id="personal-recs" class="related-product"></div>
<?php endif;?>

<?php $fullPath = $block->getRequest()->getFullActionName(); ?>
<?php if($fullPath!="subscription_index_list"):?>
    <?php if($block->getRegistry()->registry('current_product')):
    $product_data = $block->getRegistry()->registry('current_product')->getData(); ?>
    <!-- <script>ScarabQueue.push(['view', '<?php echo $product_data["entity_id"]; ?>']);</script> -->
<?php endif; ?>

<script type="text/html" id="related-template">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Related Products</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_related">
        <div class="recommended-outer">
            <div class="recommended-list related owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ 
            var p = SC.page.products[i];
            var count_total_images = p.c_number_of_slides;
            var remaining = p.c_number_of_slides-3;
            first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
            first_thumbnail = p.c_thumbnail_1;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;                
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" 
                new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"
                src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                data-src="{{= p.image }}" >
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>
<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED',
        containerId: 'related-recs',
        limit: 30,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>
<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED_2',
        containerId: 'related-recs2',
        limit: 30,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>
<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED_3',
        containerId: 'related-recs3',
        limit: 30,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery(".related").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });       
        }
    }]);
});
</script>
<script type="text/html" id="personal-template">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Recommended For You</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_personal">
        <div class="recommended-outer">
            <div id="personal" class="recommended-list owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                 {{ 
                var p = SC.page.products[i];
                var remaining = p.c_number_of_slides-3;
                var count_total_images = p.c_number_of_slides;
                first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
                first_thumbnail = p.c_thumbnail_1;
                second_thumbnail = p.c_thumbnail_2;
                third_thumbnail = p.c_thumbnail_3;
                fourth_thumbnail = p.c_thumbnail_4;
                fifth_thumbnail = p.c_thumbnail_5;
                sixth_thumbnail = p.c_thumbnail_6;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}"
                new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"        
                src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>"
                data-src="{{= p.image }}" > 
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}                   
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>
<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'PERSONAL',
        containerId: 'personal-recs',
        limit: 30,
        templateId: "personal-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery("#personal").owlCarousel({
                navigation : true,
                nav:true,
                pagination:false,
                items : 5,
                itemsCustom : false,
                itemsDesktop : [1024, 4],
                itemsDesktopSmall : [900, 5],
                itemsTablet : [600, 3],
                itemsMobile : [479, 2],
                rewindNav : false,
                navRewind : false,
                lazyLoad: false,
                scrollPerPage : true,
                navText : ["", ""],
                dots : false,
                slideBy:5,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        slideBy:2,
                        nav:true
                    },
                    576:{
                        items:3,
                        slideBy:3,
                        nav:true
                    },
                    992:{
                        items:4,
                        slideBy:4,
                        nav:true
                    },
                    1367:{
                        items:5,
                        slideBy:5,
                        nav:true
                    }
                }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });
        }
    }]);
});
</script>

<!-- Also Bought-->
<script type="text/html" id="bought-template">
    <![CDATA[
    {{ if (SC.page.products.length) { }}
    <div class="recommended-product">
    <div class="recommended-title">
        <h4>Also Downloaded</h4>
    </div>
    <amfpc name="tatva_emarsys_product_widget_alsobought">
        <div class="recommended-outer">
            <div id="bought" class="recommended-list owl-carousel">
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                 {{ 
                    var p = SC.page.products[i];
                    var remaining = p.c_number_of_slides-3;
                    var count_total_images = p.c_number_of_slides;
                    first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
                 
                    first_thumbnail = p.c_thumbnail_1;
                    second_thumbnail = p.c_thumbnail_2;
                    third_thumbnail = p.c_thumbnail_3;
                    fourth_thumbnail = p.c_thumbnail_4;
                    fifth_thumbnail = p.c_thumbnail_5;
                    sixth_thumbnail = p.c_thumbnail_6;
         }}
         <div class="item" data-scarabitem="{{= p.id }}">
            <a class="product-image image-height" title="Lorum ipsum dolor sit amet" href="{{=p.link}}">
                <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}"
                new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}"
                src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>" 
                data-src="{{= p.image }}">
                {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                    <span class="badge-label">Animated</span>
                {{ } }}
            </a>
            <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
            </div>
        </div>
        {{ } }}
    </div>
</div>
</amfpc>
</div>
{{ } }}
]]>
</script>
<script type="text/javascript">
require(['jquery'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'ALSO_BOUGHT',
        containerId: 'bought-recs',
        limit: 30,
        templateId: "bought-template",
        success: function(SC, render)
        {
            render(SC);
            jQuery("#bought").owlCarousel({
                navigation : true,
                 //nav:true,
                 pagination:false,
                 items : 5,
                 itemsCustom : false,
                 itemsDesktop : [1024, 4],
                 itemsDesktopSmall : [900, 5],
                 itemsTablet : [600, 3],
                 itemsMobile : [479, 2],
                 rewindNav : false,
                 navRewind : false,
                 lazyLoad: false,
                 scrollPerPage : true,
                 navText : ["", ""],
                 dots : false,
                 slideBy:5,
                 responsiveClass:true,
                 responsive:{
                     0:{
                         items:2,
                         slideBy:2,
                         nav:true
                     },
                     576:{
                         items:3,
                         slideBy:3,
                         nav:true
                     },
                     992:{
                         items:4,
                         slideBy:4,
                         nav:true
                     },
                     1367:{
                         items:5,
                         slideBy:5,
                         nav:true
                     }
                 }
            });
            ddimgtooltip.init("*[rel^=imgtip]");
            jQuery('.content-trim').dotdotdot({
                callback: function (isTruncated) {},
                ellipsis: "\u2026 ",
                height: 40,
                keep: null,
                tolerance: 0,
                truncate: "word",
                watch: "window",
            });
        }
    }]);
}); 
</script>         
<?php endif; ?>


<script type="text/javascript">
    require(['jquery'], function (jQuery)
    {
        jQuery(window).load(function()
        {
            setTimeout(function()
            { 
                var recommandations_ids = ['related-recs','bought-recs','personal-recs']; 
                jQuery.each(recommandations_ids, function( index, value ) 
                {
                    var div_html = jQuery('#'+value).html();
                    if(div_html == "")
                    {
                        jQuery('#'+value).detach();
                    }
                });
            },5000); 
        });
    });
</script>