<div id="related-recs"></div>

<script type="text/html" id="related-template">
<![CDATA[
{{ if (SC.page.products.length) { }}
<div class="recommended-product">
    <div class="recommended-title">
        <h4>Related Products</h4>
    </div>
    <div class="product-grid-outer recommended-product custom_gallary_product_main_div">
        <ul class="products-grid products-grid--max-5-col box-up-sell">
            {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ 
            var p = SC.page.products[i];
            var count_total_images = p.c_number_of_slides;
            var remaining = p.c_number_of_slides-3;
            first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
            first_thumbnail = p.c_thumbnail_1;
            second_thumbnail = p.c_thumbnail_2;
            third_thumbnail = p.c_thumbnail_3;                
            fourth_thumbnail = p.c_thumbnail_4;
            fifth_thumbnail = p.c_thumbnail_5;
            sixth_thumbnail = p.c_thumbnail_6;
            thumbimg = p.c_spl_thumbnail;
         }}
            <li class="item custom_gallary_product" data-scarabitem="{{= p.id }}">
                <a class="product-image image-height" title="{{= p.title }}" href="{{=p.link}}">
                    <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}" src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>" alt ="{{= p.title }}" data-src="{{= p.image }}">
                    {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                        <span class="badge-label">Animated</span>
                    {{ } }}
                </a>
                <div class="product-info" rel='imgtip[{{= p.id }}10000]'>
                    <p class="product-name content-trim"><a title="{{= p.title }}" href="{{=p.link}}">{{= p.title }}</a></p>
                </div>
            </li>
        {{ } }}
        </ul>
    </div>
</div>
{{ } }}
]]>
</script>    
<script type="text/javascript">
require(['jquery','EmarsysWidgetJs','domReady'], function (jQuery){
    ScarabQueue.push(['recommend',
    {
        logic: 'RELATED',
        containerId: 'related-recs',
        limit: 16,
        templateId: "related-template",
        success: function(SC, render)
        {
            render(SC);
            ddimgtooltip.init("*[rel^=imgtip]");
        }
    }]);
});
</script>
