<script type="text/javascript">
require(['jquery'], function ($){
    $(document).ready(function(){
        var keyword_ids_len = jQuery('.keywords').length;
        var total_paragraph = jQuery('.post-view .blog-content-inner p').length;
        if (keyword_ids_len) {
            var keywords = jQuery('.keywords').text();
            var keyword = keywords.split(',');
            var total_keywords = keyword.length;
            var child = (Math.floor(total_paragraph / total_keywords)) - 2;
            var static_state = child;
            var i;
            for (i = 0;i < total_keywords;i++) {
                console.log("keyword data=>"+keyword[i]);
                term = i + 1;
                search = i + 1;
                search_keyword = keyword[i].replace(/\s+/g, " ").trim();
                
                jQuery("<div id='wordpress-term" + term + "'>" + keyword[i] + "</div><div id='wordpress-search" + search + "' class='wordpress-recommend'>" + search_keyword + "</div>").insertAfter(".post-view .blog-content-inner p:nth-of-type(" + child + ")");
                child = child + static_state;
            }
        }    
    });
});
    
</script>
<script type="text/javascript">
require(['jquery','Emarsysjs','jQdotdot','domReady!'], function ($){
    $(document).ready(function(){
        var test_ids_len = jQuery('[id^=wordpress-search]').length;
        var keywords = jQuery('.keywords').text();
        var term_ids_len = keywords.split(',').length;

        var test = [];
        var i;
        for (i = 1; i <= test_ids_len; i++) {
            var str1 = "#wordpress-search";
            var id = str1 + i;
            test[i] = jQuery(id).text();
            jQuery(id).empty();
        }
        var text = [];
        for (i = 1; i <= term_ids_len; i++) {
            var str1 = "#wordpress-term";
            var term = str1 + i;
            text[i] = jQuery(term).text();
            jQuery(term).empty();
        }

        var j;
        for (j = 1; j <= term_ids_len; j++) {
            //if(test[$i] !== null){
            if (test[j] != null) {
                ScarabQueue.push(['searchTerm', test[j]]);
                ScarabQueue.push(['recommend',
                {
                    logic: 'SEARCH',
                    containerId: 'wordpress-search' + j,
                    limit: 5,
                    templateId: "wordpress-template" + j,
                    success: function(SC, render) {
                        render(SC);
                        ddimgtooltip.init("*[rel^=imgtip]");
                    }
                }]);
                ScarabQueue.push(['go']);
            }
        }
    });
});
    
</script>
<?php
$blockObj= $block->getLayout()->createBlock('FishPig\WordPress\Block\Post\View');
$post = $blockObj->getPost();
if($post)
{
    $keywords = $blockObj->getKeywords($post->getId());
    $keywords = explode(",", $keywords);
    for ($i = 0; $i < count($keywords); $i++) {
    if($keywords[$i] == "" || $keywords == null)
    {
        break;
    }
    ?>
    <script type="text/html" id="wordpress-template<?php echo $i+1; ?>">
        <![CDATA[
                    {{ if (SC.page.products.length) { }}
                        <div class="recommended-title-top">
                            <h5>Sample Premium Templates - <?php echo $keywords[$i]; ?>  </h5>
                        </div>
                        <div class="products-grid-outer">
                            <ul class="wordpress-img products-grid products-grid--max-5-col pro-image">
                                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                                    {{ 
                                        var p = SC.page.products[i];
                                        var remaining = p.c_number_of_slides-3;
                                        var count_total_images = p.c_number_of_slides;
                                        first_thumbnail = second_thumbnail = third_thumbnail = fourth_thumbnail = fifth_thumbnail = sixth_thumbnail = "NA";
                                
                                        first_thumbnail = p.c_thumbnail_1;
                                        second_thumbnail = p.c_thumbnail_2;
                                        third_thumbnail = p.c_thumbnail_3;
                                        fourth_thumbnail = p.c_thumbnail_4;
                                        fifth_thumbnail = p.c_thumbnail_5;
                                        sixth_thumbnail = p.c_thumbnail_6;
                                    }}
                                <li class="item" data-scarabitem="{{= p.id }}">
                                    <a class="product-image image-height" title="{{= p.title }}" href="{{= p.link }}" target="_blank">
                                        <img class="small_image_hover lazyload" rel='imgtip[{{= p.id }}10000]' title ="{{= p.title }}" product_name ="{{= p.title }}" product_url = "{{= p.link }}" remaining = "{{=remaining}}" zoomsrc="{{= first_thumbnail }}" zoomsrc2="{{= second_thumbnail }}" zoomsrc3="{{= third_thumbnail }}" new_remaining = "{{=(count_total_images - 6)}}" total_images ={{= count_total_images}} zoomsrc4="{{= fourth_thumbnail }}" zoomsrc5="{{= fifth_thumbnail }}" zoomsrc6="{{= sixth_thumbnail}}" src="<?php echo $this->getSkinUrl('images/899.gif'); ?>" data-src="{{= p.image }}" >
                                        {{  if(p.category && p.category.indexOf('Animated>') !== -1) { }}
                                            <span class="badge-label">Animated</span>
                                        {{ } }}
                                    </a>
                                  <div class="product-info name-only">
                                    <h2 class="product-name"><a class="css-content-trim-3-line" rel='imgtip[{{= p.id }}10000]' title="{{= p.title }}" href="{{= p.link }}" target="_blank">{{= p.title }}</a></h2>
                                  </div>
                                </li>
                                {{ } }}
                            </ul>
                        </div>
                    {{ } }}
                ]]>
    </script>
<?php
}
}

?>



<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.wordpress-post-view .wordpress-recommend .products-grid-outer img').attr({
            'data-pin-no-hover': 'true',
            'data-pin-nopin': 'true'
        });
    });
    jQuery(window).load(function() {
        jQuery('.wordpress-recommend').each(function() {
            if (jQuery(this).is(':empty')) {
                jQuery(this).remove();
            }
        });
    })
</script>