<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php
	$_item = $block->getItem();
	$product = $_item->getProduct();
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
	<?php if ($product->getTypeId() != \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE): ?>
	    <a class="action action-edit"
	       href="<?= /* @escapeNotVerified */ $block->getConfigureUrl() ?>"
	       title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
	        <span>
	            <?= /* @escapeNotVerified */ __('Edit') ?>
	        </span>
	   </a>
	<?php endif ?>
<?php endif ?>
