<div id="owl-demo-testimonial" class="owl-carousel owl-theme"> 
	<div class="item">
  		<p class="testimonial-content">...above and beyond expectations</p>
		<p class="testimonial-author">- Gabrielle Costigan, CEO Linfox</p>
  	</div>
  	<div class="item">
  		<p class="testimonial-content">...make sure you SlideTeam that presentation</p>
		<p class="testimonial-author">- Chris L., Global Procurement, Takeda Pharmaceuticals</p>
  	</div>
  	<div class="item">
		<p class="testimonial-content">...ecstatic with the product</p>
		<p class="testimonial-author">- Robert Bateman, President, STS Talent Management LLC</p>
	</div>
	<div class="item">
		<p class="testimonial-content">Their ability to understand my needs and turn my handwritten slides or collection of thoughts into a visually stimulating presentation is really impressive.</p>
		<p class="testimonial-author">- Alfredo Sciascia, VP Strategic Planning Group, American Express</p>
	</div>
	<div class="item">
		<p class="testimonial-content">I provided some mockup slides and asked for something appropriate for a  C-Suite meeting. The result was amazing...</p>
		<p class="testimonial-author">- Kevin Mackay, Business Development, Company name under NDA</p>
	</div>
</div>

<script type="text/javascript">
	require([
		'jquery',
		'design_service_slider_general',
		'design_service',
		'reflection',
		'design_service_slider'
		],function($) {
	})
    

</script>