<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="data item content" id="reviews" data-role="content" aria-labelledby="tab-label-reviews" role="tabpanel" aria-hidden="false">
    <div id="product-review-container" data-role="product-review"></div>
    <?php echo $this->getLayout()
    ->createBlock('Magento\Review\Block\Form')
    ->toHtml(); ?>
</div>

<script type="text/x-magento-init">
        {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>