<div class="modal fade-flip in discount" id="flipModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" id="close-btn" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">×</span></button>

      </div>
      <div class="modal-body offer_coupon">
        <h2>But before you go…</h2>
        <p class="para">Last chance to get </p>
        <h1>40% discount</h1>
        <p class="subc_p">on all the <span class="subsc"> subscriptions! </span></p>


        <div class="input-group mb-3 cp-code">
          <p class="coupon_code"> <span class="coupon_custom">Coupon Code : </span>
            <input type="text" id="copy-code" class="form-control" value="" readonly=""> <span
              class="copy_code_custom"><button type="button" id="copy" onclick="myFunctionCopy()">Copy
                Code</button></span></p>
          <!-- <div class="input-group-append">
<button class="btn btn-primary btn-copy js-btn-copy" data-clipboard-target="#copy-code" type="button">Tap To Copy</button>
</div> -->
        </div>
        <span class="hr_custom"></span>
        <p class="special_offer_custom">Offer valid for 24 hours.</p>

      </div>
      <div class="modal-footer button_action">
        <button type="button" class="btn btn-default button_1" data-dismiss="modal"> I love discounts</button>
        <button type="submit" class="btn btn-default button_2" data-dismiss="modal"> No, delete my
          account</button>
      </div>
    </div>
  </div>
</div>