<div class="topbrochure_banner">
    <div class="main-wrapper clearfix">
        <div class="conatiner">
            <div class="resubanner_text">
                <h1>Document <span class="resme_templtes">Reports</span></h1>                
            </div>            
        </div>
    </div>
</div>
<div class="subcategory-container">
	<?php echo $this->getChildHtml("custom.category.subcategories"); ?>
</div>