<form class="bug_bounty_form" id="bugbounty_form" name="bugbounty_form" method="POST" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}'>
    <h4>SlideTeam Bug Report</h4>
        <ul class="form-style-custom">
            <li>
                <div class="portf_form1">
                    <label>Name <span class="required">*</span></label>
                    <input type="text" name="name" id="name" class="field-divided" placeholder="" maxlength="64" data-validate="{required:true}"/>
                    <div class="mage-error" id="name-error" generated="true"></div>
                </div>
                <div class="portf_form1 portf_form2">
                    <label>E-mail ID <span class="required">*</span></label>
                    <input type="email" name="email" class="field-divided" placeholder="" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </li>
            <li>
                <label>Comment <span class="required">*</span></label>
                <textarea name="comment" id="comment" class="field-long field-textarea" placeholder="" data-validate="{required:true}" cols="30" rows="5" maxlength="2000"></textarea>
                <div class="allforms-comment-msg"><?php echo __("Max length should be 2000 character."); ?></div>
            </li>
            <li class="bug_file_attach">
                <div class="bug_file_attachment">
                    <label>Attachment</label>
                    <!-- <input type="file" id="fileUpload"> -->
                    <div id="mulitplefileuploader" class="multibox">
                        <label>Choose a file</label>
                        <span>No File Chosen</span>
                    </div>
                    <div id="status"></div>
                    <input id ="filesToAttach" type ="hidden" name="filesToAttach" />
                </div>
            </li>
            <li class="portf_form_custom bounty_form_custom">
                <!-- <div class="portf_form1 bug_form_captcha">
                </div> -->
                <div class="captcha-wrapper">
                        <?php
                        $blockPath = 'Magento\Captcha\Block\Captcha';
                        $block = $this->getLayout()->createBlock($blockPath);
                        $cap_data = array('form_id' => 'bugbounty_form_captcha', 'img_width' => '50');
                        $block->setData($cap_data);
                        echo $block->toHtml();
                        ?>
                </div>
            </li>
            <li class="bug_btn_center">
                <button class="submit_portf_btn" id="finalSubmit" type="submit">Submit a Bug Report</button>
            </li>
        </ul>
</form>
<script type="text/javascript">
require(['jquery','mage/mage','JQForm','uploadFileJS','jquery/jquery-ui-1.9.2'], function ($) {
      
    $(document).ready(function () {

        //$("label:contains('Please type captcha here')").remove();
            $('#bugbounty_form').find('input[name*="captcha"]').attr("placeholder", "Please Type Captcha Here");
            $('#bugbounty_form').find('input[name*="captcha"]').css('padding-left', '12px');

            $('.captcha-img').remove();
            $('<img alt="<?= $block->escapeHtmlAttr(__('Please type captcha here')) ?>" class="spinner-img" height="50" width="50" src="<?= $block->getViewFileUrl('Magento_Cms::images/popup/spinner.gif') ?>"/>').insertBefore('.captcha-reload');
            $.ajax({
                type: 'POST',
                url: '<?php echo $block->getUrl('captcha/refresh');?>',  
                data:'formId=bugbounty_form_captcha',
                success:function(data) {
                    $('.spinner-img').hide();
                    $('<img alt="<?= $block->escapeHtmlAttr(__('Please type captcha here')) ?>" class="captcha-img" height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>" src="'+ data.imgSrc +'"/>').insertBefore('.captcha-reload'); 
                    return false;                 
                }
        });

        $(document).on('click','.ui-button-text', function(){
            var filesattach = document.getElementById("filesToAttach").value;
            if(filesattach == ""){
                $('#mulitplefileuploader span').show();
                $('.file-error').empty();
            }
            else{
                $('#mulitplefileuploader span').hide();    
            }
        });

    var settings = 
      {
        url: "<?php echo $block->getUrl('bugbounty/index/save'); ?>",
        method: "POST",
        allowedTypes: "pdf, ppt, pptx,doc, docx, jpg, jpeg, png, gif, xlsx, xlsm, xlsb, xls, xltx, xltm, xlt, csv, xlam, xla, ods, zip, txt",
        maxFileSize: 5242880,
        sizeErrorStr: " is greater than 5 MB. Please reduce the size of the attachment(s) or use Dropbox/Google Drive or a similar tool to send us the attachment(s). OR Send the attachment directly via email to <a href='mailto:design@slideteam.net'>design@slideteam.net</a>",
        fileName: "myfile",
        uploadStr: jQuery(".multibox").html(),
        multiple: true,
        nestedForms:false,
        dragDropStr:"",
        onSuccess: function (files, data, xhr)
        {
          var file_data = jQuery.parseJSON(data);                   
          $('<input>').attr({
            class: 'file-bugbounty',
            type: 'hidden',
            name: file_data.original + "[]",
            value: file_data.modified
          }).appendTo('#bugbounty_form');
          $('#mulitplefileuploader span').hide();
        },
        onError: function (files, status, errMsg)
        {                    
          $("#status").html(errMsg);
        },
        onSelect:function(file)
        {
          if(file[0].size > 5242880)
          {
            //$('#finalSubmit').hide();
          } else {
            $('#finalSubmit').show();
          }
        }
      };

      $("#name").on("keyup",function() {
              var maxLength = $(this).attr("maxlength");
              if(maxLength == $(this).val().length) {
                //$('#comment-error').hide();
                $('#name-error').show();
                $('#name-error').html('Allowed only 64 characters')
              }else{
                $('#name-error').hide();
              }
        });

      $("#comment").on("keyup",function() {
        var maxLength = $(this).attr("maxlength");
        if(maxLength == $(this).val().length) {
          $('#comment-error').hide();
          $('.allforms-comment-msg').show();
        }else{
          $('.allforms-comment-msg').hide();
        }
      });

      $("#mulitplefileuploader").uploadFile(settings);
      var dataForm = $('#bugbounty_form');
      var ignore = null;

      dataForm.mage('validation', 
      {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
      }).find('input:text').attr('autocomplete', 'off');

      $('#finalSubmit').click(function(){

        $(".captcha-error").empty();
        
        $('.ajax-file-upload > form > input').unwrap(); 

        if(dataForm.validation('isValid') === false)
        {
            $("#mulitplefileuploader").uploadFile(settings);
                return false;
        }

        if(dataForm.validation('isValid')==true)  
        {
          $.ajax({
            type:'POST',
            url: '<?php echo $this->getUrl("bugbounty/index/sendEmail");?>',
            data: dataForm.serialize(),
            dataType:'json',
            showLoader: true ,//use for display loader
            success: function(data){

            if(data.status == "CaptchaError")
            {
                $('.file-error').empty();
                $(".captcha-error").empty();
                $('.mage-error').empty();
                //$( ".ajax-file-upload-container").empty();
                $(".ajax-file-upload-error").empty();
                //$("input[type=text], input[type=email],input[type=hidden] , textarea").val("");
                //$('#bugbounty_form .invalid-captcha').show();
                $("input[name='captcha[bugbounty_form_captcha]']").val("");
                $( ".customer-captcha-wrapper" ).append( "<div class='captcha-error invalid-captcha'><strong>Please enter valid captcha code.</strong></div>" );
                $('#bugbounty_form').find('input[name*="captcha"]').focus();  
                return false;
            }
            else if(data.status == "totalfileziseerror")
              {
                $('.file-error').empty();
                //$("input[type=text], input[type=email] , textarea").val("");
                $( ".multibox" ).append( "<div class='file-error'><strong>Total file size should not be greater then 5MB.</strong></div>" );
                //$( ".ajax-file-upload-error:first-child" ).addClass( "extra-class" );
                return false;
              }
              else if(data.status == "extentionerror")
              {
                $('.file-error').empty();
                //$("input[type=text], input[type=email] , textarea").val("");
                $( ".multibox" ).append( "<div class='file-error'><strong>Extension not allowed</strong></div>" );
                return false;
              }
              else if(data.status == "mailerror")
              {
                alert('Unable to send mail')
                return false;
              }
              else if(data.status == "Error")
              {
                alert('Please fill up reruired filed')
                return false;
              }
              else if(data.status=="Success")
              {
                  window.location.href = data.url;
              }
            }
          });
          return false;
        }
    });

    });
});
</script>