<script type="text/javascript">
    require(['jquery', 'tipso', 'smk_accordion','domReady!'], function (jQuery) {
        jQuery(document).ready(function () {
            // Faq Accordion
            setTimeout(function(){ jQuery(".tip").tipso({position: 'left',size: 'large',background: '#deeff7' ,color: '#000'}); }, 500);
            
            jQuery(".faq-accordion").smk_Accordion({
                closeAble: true, //boolean
            });
        });       
    });
</script>

