<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
	$url = $objectManager->get('\Magento\Framework\UrlInterface');
	$baseUrl = $url->getBaseUrl();
?>

<p><?= __("<a href=".$baseUrl.">Click here</a> to go to the homepage."); ?></p>

