<?php

$session_var = $this->getCustomerSession()->getData($this->getPageType());
$form_email = null;
$name = null;
$comment = null;
$telephone = null;

if ($session_var && is_array($session_var)) {
	foreach ($session_var as $form) {
		$name = $form['name'];
		$form_email = $form['form_email'];
		$comment = $form['comment'];
		$telephone = $form['telephone'];
	}
}

$this->getCustomerSession()->unsetData($this->getPageType());

$captchaFormId =$this->getModel()->getCaptchaFormId();
?>
<div class="<?= $block->escapeHtml(__($this->getClassNameData())) ?>">
	<label class="form-title"><?= $block->escapeHtml(__($this->getPageTypeData())) ?></label>
	
	<?php if(strcmp($this->getPageType(), 'business_research_services') == 0): ?>
		<div class="business-research-span">Fill in your research requirements and we will get back to you within 24 business hours</div>
	<?php endif ?>

	<div class="main-wrapper">
		<form name="customdesignsubcategories_form" id="customdesignsubcategories_form" method="POST" action="<?php echo $this->getUrl('customdesignsubcategories/index/sendEmail'); ?>" class="customdesignservice-form" enctype="multipart/form-data">
			<div class="clearfix form-top-block">
				<div class="col">
					<div class="input-box">
						<input name="name" id="name" title="Name" value="<?php if ($name) {echo $name;} ?>" class="input-text required-entry form-control" type="text" placeholder="Name">
					</div>
				</div>
				<div class="col">
					<div class="input-box">
						<input name="form_email" id="form_email" title="Email" value="<?php if ($form_email) {echo $form_email;} ?>" class="input-text required-entry validate-email form-control" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" placeholder="Email">
					</div>
				</div>
				<div class="col last">
					<div class="input-box">
						<input name="telephone" id="telephone" maxlength="15" title="Telephone" value="<?php if ($telephone) {echo $telephone;} ?>" class="input-text form-control maximum-length-15" data-validate="{'no-whitespace':true,'telephoneValidation':true,'validate-length':true}" type="tel" placeholder="Telephone (Optional)">
						<div class="mage-error" id="tel-error" generated="true"></div>
					</div>
				</div>
			</div>
			<div class="field col-1">
				<div class="input-box">
					<textarea name="comment" id="comment" title="Comment" class="required-entry input-text form-control" placeholder="Your message" cols="30" rows="5" maxlength="2000"><?php if ($comment) { echo $comment; } ?></textarea>
					<div class="allforms-comment-msg"><?php echo __("Max length should be 2000 character."); ?></div>
				</div>
			</div>
			<div class="clearfix inner-attach">
				<div class="attach-block clearfix">
					<div id="mulitplefileuploader" class="box"><label><img src="<?php echo $this->getViewFileUrl('Tatva_Customdesignsubcategories::images/attachment.png'); ?>" alt="Attachment" /><span>Attach a file</span></label></div>
					<input id ="filesToAttach" type ="hidden" name="filesToAttach" />
				</div>
				
				<span class="tip top-right tipso_style" data-tipso="Please upload any mockups, presentations, sketches, back of napkin designs etc. <br>NOTE: Please use dropbox or you sendit and send us the link if the attachment is greater than 25 MB, or mail them separately to design@slideteam.net"> <a class="tooltips"><em><img src="<?php echo $this->getViewFileUrl('Tatva_Customdesignsubcategories::images/info.png'); ?>" alt=""></em></a></span>

				<div class="captcha-wrapper">
					<?php
				    	$blockPath = 'Magento\Captcha\Block\Captcha';
				    	$block = $this->getLayout()->createBlock($blockPath);
				        $cap_data = array('form_id'=>'<?php echo $captchaFormId;?>','img_width'=>'50');
				        $block->setData($cap_data);
				        echo $block->toHtml();
				    ?>
					<?php //echo $block->getChildHtml('form.additional.info'); ?>
				</div>
				
				<div class="formbtn-wrap">
					<button id="finalSubmit" title="Submit" class="action submit primary"><span>Submit</span></button>
					<img src="<?= $block->getViewFileUrl('Tatva_Wishlist::images/removing.gif') ?>" id="loaderImage" style="display:none">
				</div>
			</div>

			<div class="explore-more">
				<?php $currentPage = $this->getPageType(); ?>
				<?php if (in_array($currentPage, array('custom-business-slides','flat-powerpoint-designs','custom-powerpoint-diagrams','custom-powerpoint-themes'))){?>
					<p>or</p>
					<a href="<?php echo $this->getUrl('powerpoint_presentation_design_services'); ?>">Explore More Custom Design Service From Us</a>
					<script type="text/javascript">
						require(['jquery','customdesignsubcategoriesJS'], function ($){});
					</script>
				<?php } ?>
			</div>
		</form>
	</div>
</div>


<script type="text/javascript">
	require(['jquery','Magento_Customer/js/customer-data','JQForm','uploadFileJS','tipso','mage/mage','Magento_Theme/js/lazyload/lazy','jquery/jquery-ui-1.9.2'], function ($,customerData)
	{
		$(document).ready(function () 
		{
			$("label:contains('Please type captcha here')").remove();
            $('#customdesignsubcategories_form').find('input[name*="captcha"]').attr("placeholder", "Please type captcha here");
            $('#customdesignsubcategories_form').find('input[name*="captcha"]').css('padding-left', '12px');

			$('<img alt="<?= $block->escapeHtmlAttr(__('Please type captcha here')) ?>" class="spinner-img" height="50" width="50" src="<?= $block->getViewFileUrl('Magento_Cms::images/popup/spinner.gif') ?>"/>').insertBefore('.captcha-reload');
			$.ajax({
        		type: 'POST',
		        url: '<?php echo $block->getUrl('captcha/refresh');?>',  
		        data:'formId=<?php echo $captchaFormId;?>',
		        success:function(data) {
		        	$('.spinner-img').hide();
		        	$('<img alt="<?= $block->escapeHtmlAttr(__('Please type captcha here')) ?>" class="captcha-img" height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>" src="'+ data.imgSrc +'"/>').insertBefore('.captcha-reload'); 
		        	return false;                 
                }
            });

            var telval = jQuery('#telephone').val();
            jQuery('#telephone').on('keydown',function(){
                var tellength  = jQuery('#telephone').val().length;
                if((tellength+1) == 16)
                {
                    jQuery('#tel-error').show();
                    jQuery('#tel-error').html('Allowed only 15 characters');
                    jQuery('#telephone-error').hide();
                }
            })
		
			var settings = 
			{
				url: "<?php echo $block->getUrl('customdesignsubcategories/index/save'); ?>",
				method: "POST",
				allowedTypes: "pdf, ppt, pptx,doc, docx, jpg, jpeg, png, gif, xlsx, xlsm, xlsb, xls, xltx, xltm, xlt, csv, xlam, xla, ods, zip, txt",
				maxFileSize: 5242880,
				sizeErrorStr: " is greater than 5 MB. Please reduce the size of the attachment(s) or use Dropbox/Google Drive or a similar tool to send us the attachment(s). OR Send the attachment directly via email to <a href='mailto:design@slideteam.net'>design@slideteam.net</a>",
				fileName: "myfile",
				uploadStr: jQuery(".box").html(),
				multiple: true,
				nestedForms:false,
				dragDropStr:"",
				onSuccess: function (files, data, xhr)
				{
					var file_data = jQuery.parseJSON(data);                   
					$('<input>').attr({
						type: 'hidden',
						name: file_data.original + "[]",
						value: file_data.modified
					}).appendTo('form');

				},
				onError: function (files, status, errMsg)
				{                    
					$("#status").html(errMsg);
				},
				onSelect:function(file)
				{
					if(file[0].size > 5242880)
					{
						//$('#finalSubmit').hide();
					} else {
						$('#finalSubmit').show();
					}
				}
			};

			setTimeout(function(){$("#mulitplefileuploader").uploadFile(settings)},1000);
			var dataForm = $('#customdesignsubcategories_form');
			var ignore = null;

			dataForm.mage('validation', 
			{
				ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
			}).find('input:text').attr('autocomplete', 'off');

			setTimeout(function() {
				$(".tip").tipso({position: 'left',size: 'large'});
			}, 1000);

			// task 1344
			$("#comment").on("keyup",function() {
			  var maxLength = $(this).attr("maxlength");
			  if(maxLength == $(this).val().length) {
			  	$('#comment-error').hide();
			    $('.allforms-comment-msg').show();
			  }else{
			    $('.allforms-comment-msg').hide();
			  }
			});
			// task 1344 end
		});

	}); 
</script>

<?php if(strcmp($this->getPageType(), 'professional_word_formatting_services') == 0): ?>
	<script type="text/javascript">
		require(['jquery','word_formatting_servicesJS'], function ($){
		});
	</script>
<?php endif ?>

