<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<div id="comments" class="comments-wrapper">
	<?php if (count($comments) > 0): ?>
		<?php if ($this->getCommentCount() == 1): ?>
			<h5><?php echo __('One thought on &ldquo;%1&rdquo;', $this->escapeHtml($post->getPostTitle())) ?></h5>
		<?php else: ?>
			<h5><?php echo __('%1 thoughts on &ldquo;%2&rdquo;', $this->getCommentCount(), $this->escapeHtml($post->getPostTitle())) ?></h5>
		<?php endif; ?>
		<?php echo $this->getCommentsHtml() ?>
		<?php echo $this->getPagerHtml() ?>
	<?php endif; ?>
	<?php echo $this->getFormHtml() ?>
</div>
