<?php
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
//Base Url without index.php 
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$product =$objectManager->get('Magento\Framework\Registry')->registry('current_product');
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php
/* @escapeNotVerified */ $json = $block->getGalleryImagesJson();
$array = json_decode($json, true);
?>
<div id="images_populate" class="products-grid-outer images-populate">
    <h4><?php echo $product->getName(); ?><?= /*@escapeNotVerfied*/__(' with all ');?><?php echo count($block->getGalleryImages())?><?= /*@escapeNotVerfied*/__(' slides');?></h4>
    <p><p class="product-gallery-sub-title"><?php echo $product->getResource()->getAttribute('sentence2')->getFrontend()->getValue($product)?></p></p>
    <ul class="products-grid products-grid--max-5-col box-up-sell">
        <?php
        foreach ($array as $item) {
            $imgurl = $item['thumb'];
            ?>
            <li class="item">
                <a><img src="<?php echo $imgurl; ?>"></a>
            </li>
            <?php
        }
        ?>
    </ul>
</div>


