<div id="maincontent" class="coupon_page">
	<div class="coupn_bar">
		<div class="main-wrapper clearfix">
			<div class="conatiner">
				<div class="row coupon_topsec">
					<img class="coupen_rghtimg lazyload" src="<?php echo $this->getViewFileUrl('images/89.gif'); ?>" data-src="<?php echo $this->getViewFileUrl('Tatva_Couponcode::images/coupon_rightimg.png'); ?>" alt="">
					<div class="coupn_lefttext">
						<h2>SlideTeam Coupon Codes</h2>
						<p>
							Score the savings you want with these discount codes. By placing your order using
							these coupon codes you are accepting all these Terms &amp; Conditions stated by
							SlideTeam. Customers must adhere to all these terms and conditions while making their
							purchase using these discount coupons. These codes can be used to avail discounts on
							the products available on SlideTeam. Enter the code available at the checkout page to
							claim your discount. Coupon codes are available for a specific customer and cannot be
							transferred to others. Each coupon is intended for single use. Redemption of any
							coupon is prohibited after the expiry date. Coupons cannot be reinstated under any
							circumstances. Two offers cannot be combined together. The rights to all these
							coupons are reserved by SlideTeam, they can discontinue these at any time.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>