<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder()?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems();?>
           <tr >
                <td style="font-family:Verdana;Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;padding:0;margin:0">
                    <table style="border-collapse:collapse;padding:10px 15px;margin:0;width:100%" cellpadding="0" cellspacing="0" border="0">
                    <thead>
                        <tr>
                            <th style="width:57%;font-family:Verdana;Arial;font-weight:700;padding:10px 15px;background:#f1f1f1;text-transform:uppercase;text-align:left;font-size:11px"> <?=/* @escapeNotVerified */__('ITEM')?> </th>
                            <th style="font-family:Verdana,Arial;font-weight:700;padding:10px 15px;background:#f1f1f1;text-transform:uppercase;text-align:center;font-size:11px"> <?=/* @escapeNotVerified */__('SKU')?> </th>
                            <th style="font-family:Verdana,Arial;font-weight:700;padding:10px 15px;background:#f1f1f1;text-transform:uppercase;text-align:center;font-size:11px">  <?=/* @escapeNotVerified */__('QTY')?> </th>
                            <th style="font-family:Verdana,Arial;font-weight:700;padding:10px 15px;background:#f1f1f1;text-transform:uppercase;text-align:right;font-size:11px">  <?=/* @escapeNotVerified */__('PRICE')?> </th>
                        </tr>
                    </thead>    
                    </table>
                </td>
            </tr>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getParentItem()): ?>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <tbody>
                                <?=$block->getItemHtml($_item)?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            <?php endif;?>
        <?php endforeach;?>
        <tfoot class="order-totals">
            <?=$block->getChildHtml('order_totals')?>
        </tfoot>
    </table>


<?php endif;?>
