<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */

/** @var \Magento\Captcha\Model\DefaultModel $captcha */

$captcha = $block->getCaptchaModel();
?>
<div class="field captcha required" role="<?= $block->escapeHtmlAttr($block->getFormId()) ?>">
    <label for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" class="label captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"><span><?= $block->escapeHtml(__('Please type captcha here')) ?></span></label>
    <div class="customer-captcha-wrapper clearfix">
        <div class="control captcha col">
            <input name="<?= $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE) ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]" type="text" class="input-text required-entry" data-validate="{required:true}" id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" />
        </div>
        <div class="nested col">
            <div class="field captcha no-label"
                 data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
                 data-mage-init='{"captcha":{"url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
                                             "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"}}'>
                <div class="control captcha-image">
                    <img alt="<?= $block->escapeHtmlAttr(__('Please type captcha here')) ?>" class="captcha-img" height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>" src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"/>
                    <img id="captcha-reload" class="action reload captcha-reload" title="<?= $block->escapeHtmlAttr(__('Reload captcha'))?>" src="<?php echo $this->getViewFileUrl('Magento_Captcha::images/reload.png'); ?>" alt="Reload captcha">
                </div>
            </div>
            <?php if ($captcha->isCaseSensitive()) :?>
                <div class="captcha-note note">
                    <?= $block->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']) ?>
                </div>
            <?php endif; ?>
            <div class="invalid-captcha" style="display: none">
                <?= $block->escapeHtml(__('<strong>Please enter valid captcha code.</strong>'),['strong']) ?>
            </div>
        </div>
    </div>
</div>
