<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<?php 
$blockObj= $block->getLayout()->createBlock('Tatva\Customer\Block\Form\Edit'); 
$customertype = $blockObj->getCustomerLoginType($block->getCustomer()->getId());
?>
<div class="dashboard">
    <div class="welcome-msg">
        <p class="hello"><strong><?= $block->escapeHtml(__('Hello ')) ?><?= $block->escapeHtml($block->getName()) ?></strong></p>
        <p><?= $block->escapeHtml(__('From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.'))?></p>
    </div>
</div>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <h3><?= $block->escapeHtml(__('Contact Information')) ?></h3>
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
            </div>
            <div class="box-actions">
                
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
       
    </div>
</div>
<?php if($customertype == null) : ?>
<script type="text/javascript">
            require([
                "jquery",
            ], function($){
            $(".box-actions").css("display", "block");
        });
</script>
<?php endif; ?>
