<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$Imagehelper = $this->helper('Tatva\Theme\Helper\Header');
$imageUrl = $Imagehelper->getBase(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product';
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$ebookHelper = $this->helper('Tatva\Ebook\Helper\Ebook');
$productObj = $ebookHelper->loadProductById($_item->getProductId());
$isEbook = $productObj->getIsEbook();
$productImage = $productObj->getImage();
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item cart-item">
            <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            <?php if($isEbook == 1) { ?>
                <img src="<?= $imageUrl.$productImage ?>">
            <?php } ?>
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <!-- <span class="product-item-photo"> -->
            <?php endif;?>
            <!-- <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?> -->
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
               <!--  </span> -->
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if($isEbook != 1) { ?>
                    <?php if ($_options = $block->getOptionList()):?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) : ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <?php if(($_option['label'] == "Start Date") || ($_option['label'] == "Billing Period")) : ?>
                                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                    <dd>
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                            <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                        <?php else: ?>
                                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                        <?php endif; ?>
                                    </dd>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
                <?php } ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <?php if($isEbook == 1) { ?>
            <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                <div class="field qty">
                    <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                        <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                    </label>
                    <span><?php  echo $block->getQty()?></span>
                    <!-- <div class="control qty">
                        <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                               name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                               value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                               type="number"
                               size="4"
                               title="<?= $block->escapeHtml(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </div> -->
                </div>
            </td>
        <?php } ?>
        <!-- <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                           name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td> -->

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
        <td colspan="100" class="remove">
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
    <!-- <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr> -->
    <?php if($isEbook == 1) { ?>
        <tr>
            <td colspan="5" class="ebook-text">
                <b>NOTE</b>
                <p>1. You will get an email with a PDF link to your eBook(s). You can download it anytime by opening your email.</p>
                <p>2. You can go back to the eBook page and you can download your eBook(s) directly by clicking the download button.</p>
                <p>3. If you have questions or need assistance in completing your order,feel free to contact us at any time.<a href="tel:+14086594170" title="+ 1(408) 659-4170"><b class="ebook-number"> + 1(408) 659-4170</b></a>
                </p>
            </td>
        </tr>
    <?php } ?>
</tbody>