<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$customcollection = $block->getIsCustomProducts();

$currentCategory = $block->getCurrentCategory();
$_productCollection = $block->getLoadedProductCollection();
$productCollectionSize = $_productCollection->getSize();

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$backendModel = $_productCollection->getResource()->getAttribute('media_gallery')->getBackend();
$_category = $block->getCurrentCategoryFromRegistry();
$small_image_biggersize1 = "";
$small_image_biggersize2="";
$small_image_biggersize3="";
$small_image_biggersize4="";
$small_image_biggersize5="";
$small_image_biggersize6="";
if($_category): $parent_category_name = $_helper->categoryAttribute($_category, $_category->getParentCategory()->getName(), 'name');endif;
?>
<?php if (!$productCollectionSize): ?>
    <div class="container"><div class="message-wrapper"><div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div></div></div>
    <?php else: ?>
        <?= $block->getChildHtml("title_para"); ?>
        <?php if($currentCategory): ?>
            <?php if($currentCategory->getParentCategory()->getName() != "Themes"): ?>
            <div class="container">
                <div class="main-wrapper list-detail-consistency clearfix">
                    <div class="product_list_sorting">
                        <?php echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\ProductList\Toolbar')->setTemplate('Magento_Catalog::product/list/toolbar/sorter.phtml')->toHtml(); ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>    
    <?= $block->getChildHtml("filter_by_category"); ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>    
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    

    $tag_page = $this->getRequest()->getRouteName() == "tag" ? true : false;
    ?>
      
    <div class="container listing-container">        
        
        <!-- Emarsys Start -->
        <?php
        $cpBlock = $this->getLayout()->createBlock('Tatva\Bestsellers\Block\ListProduct'); 
        $emarsysStatus = $cpBlock->getConfigration()->getValue('button/emarsys_config/field1',\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
        ?>
        <?php if($emarsysStatus && $tag_page) :?>
            <div class="main-wrapper list-detail-consistency theme-wrapper clearfix">
                <div id="search-resc"> </div>
                <!-- <div id="customtopic1"></div> -->
            </div>
        <?php endif; ?>
        <!-- Emarsys End -->

        <?php if($currentCategory): ?>
            <?php if($currentCategory->getParentCategory()->getName() == "Themes"): ?>

            <!-- Custom Emarsys Start -->        
            <?php echo $this->getLayout()->createBlock('Tatva\Catalog\Block\Product\ListProduct')->setTemplate('Magento_Catalog::product/list/emarsys_popular_product.phtml')->toHtml(); ?>
            <!-- Custom Emarsys End -->
            
            <div class="main-wrapper list-detail-consistency theme-sort-wrapper clearfix">
                <!-- <h4>Our Entire Collection</h4> -->
                <div class="product_list_sorting clearfix">
                    <?php echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\ProductList\Toolbar')->setTemplate('Magento_Catalog::product/list/toolbar/sorter.phtml')->toHtml(); ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?> <?php if($tag_page){ echo "tag-list";}?>">
        
        <?php if($tag_page): ?>
            <div class="theme-wrapper tatva-theme-wrapper">
                <h2>Our Entire Collection</h2>
            </div>
        <?php endif; ?>
        
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php if($customcollection != null): ?>
                <?php echo $this->getLayout()->createBlock('Tatva\Catalog\Block\Product\ListProduct')->setTemplate('Tatva_Listingproduct::list.phtml')->toHtml(); ?>
            <?php endif; ?>
            <?php $i=0; $j=10; ?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):?>
                <?php if($_product->getTypeId() == \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php $a4id = 'ppt-product' ?>
                <?php $a4_category_id = $cpBlock->getConfigration()->getValue('A4/general/a4category', \Magento\Store\Model\ScopeInterface::SCOPE_STORE); ?> 
                <?php $a4categoryCollection = explode(",",$a4_category_id); ?>
                <?php $cats = $_product->getCategoryIds(); ?>
                <?php $result = array_intersect($a4categoryCollection, $cats); ?>
                <?php if(!empty($result)) 
                    {
                        $a4id = 'onepage-product';
                    }
                ?>
                <div class="product-item-info <?php echo $a4id; ?>" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>

                    <?php
                    $backendModel->afterLoad($_product);
                    $block->addGallery($_product);
                    $total_images = $_product->getMediaGalleryImages();

                    $small_image = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'category_page_grid')->getUrl();   
                    $small_image_str = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_page_image_medium')->getUrl();

                    $count_total_images = count($total_images);
                    $remaining = count($total_images)-3;
                    if($remaining==-3)
                    {
                        $small_image_biggersize1 =  $_product->getImageUrl();
                    }else{
                        $id =0;
                        $galary_images = array();
                        $image_url='';                
                        $is_hero_img_different = 0;
                        foreach($total_images as $val)
                        {
                            $galary_images[] = $this->helper('Magento\Catalog\Helper\Image')->init($_product,'category_page_grid')->setImageFile($val->getFile())->getUrl();
                            
                            $id++;
                            if($id >5){break;}
                        }
                        $count = count($galary_images);
                                //echo "count images:".$count;

                        $small_image_biggersize2="";
                        $small_image_biggersize3="";
                        $small_image_biggersize4="";
                        $small_image_biggersize5="";
                        $small_image_biggersize6="";
                        
                        if($remaining > 3) {
                            $small_image_biggersize1 =  $galary_images[0];
                        }else {
                            $small_image_biggersize1 = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_page_image_medium')->setImageFile($total_images->getFirstItem()->getFile())->getUrl();
                            
                        }

                        $hero_img_str = $galary_images[0];
                        $hero_img_name = substr($hero_img_str,(int)strrpos($hero_img_str,'/'));
                        $small_img_name = substr($small_image_str,(int)strrpos($small_image_str,'/'));  
                        
                        if($hero_img_name != $small_img_name){
                            $is_hero_img_different = 1;
                            if($remaining > 3) {
                                $small_image_biggersize1 = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'category_page_grid')->getUrl();
                                
                            }else {
                                $small_image_biggersize1 = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_page_image_medium')->getUrl();
                                
                            }
                            if($count > 1){
                                $small_image_biggersize2 = $galary_images[0];
                            }
                            if($count > 2){
                                $flag = strpos($galary_images[1], $small_img_name);
                                if($flag !== false){
                                    $small_image_biggersize3 =  $galary_images[2];    
                                }
                                else{
                                    $small_image_biggersize3 =  $galary_images[1];
                                }
                            }
                            if($count > 3){
                                $small_image_biggersize4 =  $galary_images[3];
                            }
                            if($count > 4){
                                $small_image_biggersize5 =  $galary_images[4];
                            }
                            if($count > 5){
                                $small_image_biggersize6 =  $galary_images[5];
                            }
                        }
                        else{
                            if($count > 1){
                                $small_image_biggersize2 = $galary_images[1];
                            }
                            if($count > 2){
                                $small_image_biggersize3 =  $galary_images[2];
                            }
                            if($count > 3){
                                $small_image_biggersize4 =  $galary_images[3];
                            }
                            if($count > 4){
                                $small_image_biggersize5 =  $galary_images[4];
                            }
                            if($count > 5){
                                $small_image_biggersize6 =  $galary_images[5];
                            }
                        }

                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php 
                            $pos = strrpos($small_image_biggersize1, '.');
                            $pathEnding = substr($small_image_biggersize1, $pos + 1);
                            if($pathEnding == 'gif') {
                                echo '<span class="bagde-label">Animated</span>';
                            }
                        ?>
                        <?php $image_result = array('key'=>$_product->getId(),'total_images'=>$count_total_images, 'remaining'=>$remaining, 'name'=>$_product->getName(),
                            'id'=>$_product->getId(),'product_url'=>$_product->getProductUrl(),'zoomsrc'=>$small_image_biggersize1,
                            'zoomsrc2'=>$small_image_biggersize2,'zoomsrc3'=>$small_image_biggersize3,
                            'zoomsrc4'=>$small_image_biggersize4,'zoomsrc5'=>$small_image_biggersize5,'zoomsrc6'=>$small_image_biggersize6,'is_new'=>1,'mainsrc'=>$small_image); ?>
                            <?= $productImage->setData('image_result',$image_result)->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name" rel="imgtip[<?php echo $_product->getId();?>]">
                                <span class="name-content-trim"><a class="product-item-link name-trim" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></span>
                            </strong>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description product-item-details">
                                    <p class="description-trim description-content-trim">
                                        <?= str_replace('</p>','',str_replace('<p>','',$_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'))) ?>
                                    </p>
                                </div>
                            <?php endif; ?>
                            <?php if($currentCategory): ?>
                                <?php if($currentCategory->getName() == 'Google Slides'): ?>
                                <?php $googleLink = $_product->getData('google_slide_link'); ?>
                                <div class="btn-google-slide">
                                    <a target="_blank" href="<?php if(isset($googleLink)): echo $googleLink; endif; ?>">Open in Google Slides</a>
                                </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                    <?php $j++; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>


    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
            }
        }
    }
</script>
<?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery','Ddimgtooltip'], function ($) 
    {
    });
</script>
