<?php
//$session_var = Mage::getSingleton('core/session')->getData('inf_params');
//$email = null;
//$name = null;
//$comment = null;
//
//if($session_var && is_array($session_var)){
//    foreach($session_var as $form){
//        $name = $form['name'];
//        $email = $form['email'];
//        $comment = $form['comment'];
//    }
//}
?>
<?php
$pageType = $block->getPageType();
?>

<div class="<?php echo $pageType ?>-submit-block">
    <div class="main-wrapper">
        <label class="form-title">Submit Your <?php echo ucwords(str_replace('_'," ",$pageType)) ?> Request</label>
        <form class="customdesignservice-form" name = "<?php echo $pageType ?>_form" id="<?php echo $pageType ?>_form" action="<?php // echo Mage::getUrl('infographic/index/sendEmail');  ?>" Method="POST" enctype="multipart/form-data">
            <div class="clearfix form-top-block">
                <div class="field col">
                    <div class="input-box">
                        <input name="name" id="name" title="Name" value="<?php // if($name){echo $name;} ?>" class="input-text required-entry form-control" type="text" placeholder="Name">
                    </div>
                </div>
                <div class="field col">
                    <div class="input-box">
                        <input name="email" id="email" title="Email" value="<?php // if($email){echo $email;} ?>" class="input-text required-entry validate-email form-control" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" placeholder="Email">
                    </div>
                </div>
                <div class="field col last">
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="Telephone" maxlength="15" value="" class="input-text form-control maximum-length-15" data-validate="{'no-whitespace':true,'telephoneValidation':true,'validate-length':true}" type="tel" placeholder="Telephone (Optional)">
                        <div class="mage-error" id="tel-error" generated="true"></div>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="input-box">
                    <textarea name="comment" id="comment" title="Comment" class="required-entry input-text form-control" placeholder="Your message" cols="30" rows="5"><?php // if($comment){echo $comment;} ?></textarea>
                </div>
            </div>
            <div class="clearfix inner-attach">
                <div class="attach-block clearfix">
                    <div id="mulitplefileuploader" class="box"><label><img src="<?php echo $this->getViewFileUrl('Tatva_Customdesignservice::images/attachment.png'); ?>" alt=""><span>Attach a file</span></label></div>
                    <div id="status"></div>
                    <input id ="filesToAttach" type ="hidden" name="filesToAttach" />
                </div>
                <button class="btn btn-default cmsform-btn" title="Submit" name="submit" id="submit" type="submit"><span><span>Submit</span></span></button>
                <span class="tip top-right tipso_style" data-tipso="Please upload any mockups, presentations, sketches, back of napkin designs etc.
                      <br>NOTE: Please use dropbox or yousendit and send us the link if the attachment is greater than 25 MB, or mail them separately to design@slideteam.net">
                    <a class="tooltips"><em><img src="<?php echo $this->getViewFileUrl('Tatva_Customdesignservice::images/info.png'); ?>" alt=""></em></a>
                </span>
            </div>
        </form>
    </div>
</div>
<<script type="text/javascript">
    require(['jquery'], function ($){
        $(document).ready(function(){
            var telval = jQuery('#telephone').val();
            jQuery('#telephone').on('keydown',function(){
                var tellength  = jQuery('#telephone').val().length;
                if((tellength+1) == 16)
                {
                    jQuery('#tel-error').show();
                    jQuery('#tel-error').html('Allowed only 15 characters');
                    jQuery('#telephone-error').hide();
                }
            })
        })
    });
</script>
