<?php $url = $block->getBaseUrl(); ?>
<script type="text/javascript">
    //Form on button click
    let modalBtns = document.querySelectorAll(".research-button");
    modalBtns.forEach(function(btn) {
        btn.onclick = function() {
          let modal = btn.getAttribute('data-modal');
          document.getElementById(modal).style.display = "block";
        }
    });
    let closeBtns = document.querySelectorAll(".form_popup_custom .close");
    closeBtns.forEach(function(btn) {
        btn.onclick = function() {
          let modal = btn.closest('.modal');
          modal.style.display = "none";
          //window.location.reload();
          window.location="<?php echo $url.'powerpoint_presentation_design_services/business_research_services'; ?>";
        }
    });
    window.onclick = function(event) {
        if(event.target.classList.contains('modal')) {
            event.target.style.display = "none";
            //window.location.reload();
            window.location="<?php echo $url.'powerpoint_presentation_design_services/business_research_services'; ?>";
        }
    }

    //Slider
    let closeBtn = document.querySelectorAll(".our_recent_work_content .close");
    closeBtn.forEach(function(btn) {
        btn.onclick = function() {
            let popup = btn.closest('.overlay')
            popup.style.display = "none";
        }
    });
    
    var slideIndex = 1;

    var slides = document.querySelectorAll(".our_recent_work_content .fancy");
    slides.forEach(function(slide) {
        slide.onclick = function() {
            let popupId = slide.getAttribute("data-popupid");
            
            let slidePopup = document.getElementById("popup"+ popupId );
    
            slidePopup.style.display = "block";
            slidePopup.style.visibility = "visible";
            slidePopup.style.opacity = "1";
            slidePopup.style.zIndex = "999";

            slideIndex = 1;
            showSlides(slideIndex ,  popupId );
        }
    });

    function plusSlides(n ,id) {
        showSlides(slideIndex += n , id);
    }

    function getcurrentSlide(n,id) {
        showSlides(slideIndex = n,id);
    }

    function showSlides(n , id) {
        var i;
        let slides =   document.querySelectorAll("#popup"+ id +"  .mySlides");
        var dots =  document.querySelectorAll("#popup"+ id +" .demo");

        if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
    }
</script>

<script type="text/javascript">
    // vars
'use strict'
var testim = document.getElementById("testim"),
        testimDots = Array.prototype.slice.call(document.getElementById("testim-dots").children),
    testimContent = Array.prototype.slice.call(document.getElementById("testim-content").children),
    testimLeftArrow = document.getElementById("left-arrow"),
    testimRightArrow = document.getElementById("right-arrow"),
    testimSpeed = 4500,
    currentSlide = 0,
    currentActive = 0,
    testimTimer,
        touchStartPos,
        touchEndPos,
        touchPosDiff,
        ignoreTouch = 30;
;

window.onload = function() {

    // Testim Script
    function playSlide(slide) {
        for (var k = 0; k < testimDots.length; k++) {
            testimContent[k].classList.remove("active");
            testimContent[k].classList.remove("inactive");
            testimDots[k].classList.remove("active");
        }

        if (slide < 0) {
            slide = currentSlide = testimContent.length-1;
        }

        if (slide > testimContent.length - 1) {
            slide = currentSlide = 0;
        }

        if (currentActive != currentSlide) {
            testimContent[currentActive].classList.add("inactive");            
        }
        testimContent[slide].classList.add("active");
        testimDots[slide].classList.add("active");

        currentActive = currentSlide;
    
        clearTimeout(testimTimer);
        testimTimer = setTimeout(function() {
            playSlide(currentSlide += 1);
        }, testimSpeed)
    }

    testimLeftArrow.addEventListener("click", function() {
        playSlide(currentSlide -= 1);
    })

    testimRightArrow.addEventListener("click", function() {
        playSlide(currentSlide += 1);
    })    

    for (var l = 0; l < testimDots.length; l++) {
        testimDots[l].addEventListener("click", function() {
            playSlide(currentSlide = testimDots.indexOf(this));
        })
    }

    playSlide(currentSlide);

    // keyboard shortcuts
    document.addEventListener("keyup", function(e) {
        switch (e.keyCode) {
            case 37:
                testimLeftArrow.click();
                break;
                
            case 39:
                testimRightArrow.click();
                break;

            case 39:
                testimRightArrow.click();
                break;

            default:
                break;
        }
    })
        
        testim.addEventListener("touchstart", function(e) {
                touchStartPos = e.changedTouches[0].clientX;
        })
    
        testim.addEventListener("touchend", function(e) {
                touchEndPos = e.changedTouches[0].clientX;
            
                touchPosDiff = touchStartPos - touchEndPos;
            
                console.log(touchPosDiff);
                console.log(touchStartPos); 
                console.log(touchEndPos);   

            
                if (touchPosDiff > 0 + ignoreTouch) {
                        testimLeftArrow.click();
                } else if (touchPosDiff < 0 - ignoreTouch) {
                        testimRightArrow.click();
                } else {
                    return;
                }
            
        })
}
</script>
 