<script type="text/javascript">
  require(['jquery', 'tipso', 'smk_accordion'], function ($) {

      $(document).ready(function () {

          // Faq Accordion
          $(".faq-accordion").smk_Accordion({
              closeAble: true, //boolean
          });
      });
      $(window).load(function () {
          $(".tip").tipso({position: 'left',size: 'large'});
      });
  });
</script>

<div class="faq-block-container">
  <div class="faq-block">
    <div class="main-wrapper clearfix">
    <h3>Frequently Asked Questions</h3>
        <div class="faq-accordion">
        <div class="row">
          <div class=" col-12">
            <div class="accordion_in">
              <h4 class="acc_head">How can I download PowerPoint eBooks?</h4>
              <div class="acc_content">
                  You need to be a SlideTeam subscriber, free or paid, to buy our eBooks.<br>
                  <b>Steps to Buy eBooks for Free Members:</b><br>
                  Click the “Buy Now” button to purchase an eBook you like. Login to your account (if you do not have any account with SlideTeam, sign up for a free account). 
                  <br>
                  Choose any of the options to buy eBooks:
                  <br>
                  1.Buy 1 eBook for $19.99<br>
                  2.Buy All eBooks for $39.99 (the best package)<br>
                  3.Get any eBook for free with our Premium subscription

                  <br><br>
                  If you choose the last option, you will be taken to the Pricing page where you can subscribe to any of our premium plans and download any eBook for free. 
                  <br><br>
                  <b>Steps to Buy eBooks for Premium Members:</b><br>
                  If you have subscribed to any of our premium plans, simply login to your SlideTeam account, go to our eBooks section, and download eBook(s) you like free of cost. 
              </div>
            </div>
            <div class="accordion_in">
              <h4 class="acc_head">Do I need to be a SlideTeam member to buy eBooks?</h4>
              <div class="acc_content">Yes, you need to be a SlideTeam member, whether free or paid, to buy our eBooks. Premium members can download our eBooks for free. Free users can buy one eBook for $19.99 or all books for $39.99.</div>
            </div>
            <div class="accordion_in">
              <h4 class="acc_head">I have a Monthly subscription. Do I get eBooks for free?</h4>
              <div class="acc_content">Yes, our eBooks are available free to members subscribed to any of our premium plans – Monthly / Semi Annual / Annual / Annual plus Custom Design / Team License. Login to your SlideTeam account, go to our eBooks section, and download the eBooks(s) you like free of cost</div>
            </div>
            <div class="accordion_in">
              <h4 class="acc_head">I have a Semi Annual subscription. Do I get eBooks for free?</h4>
              <div class="acc_content">Yes, our eBooks are available free to members subscribed to any of our premium plans – Monthly / Semi Annual / Annual / Annual plus Custom Design / Team License. Login to your SlideTeam account, go to our eBooks section, and download the eBooks(s) you like free of cost.</div>
            </div>
            <div class="accordion_in">
              <h4 class="acc_head">What methods of payments do you accept?</h4>
              <div class="acc_content">We accept payments through PayPal and Stripe. All credit cards and debit cards are accepted for payments (Visa, Mastercard, American Express and Discover).</div>
            </div>
            <div class="accordion_in">
              <h4 class="acc_head">Do you give any discounts on eBooks?</h4>
              <div class="acc_content">There is no discount on purchasing single eBooks. You can, however, buy the complete eBook collection for just $39.99 which is an unbeatable offer. Or you could also subscribe to any of our Premium plans and download all eBooks for free. Our premium subscription also gives you many attractive offerings such as template downloads and custom designs. Check our plans and offerings at https://www.slideteam.net/pricing</div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>