<?php 
	$base_url = $this->getURL();	
	//$bannerImage = $this->getViewFileUrl("Tatva_Ebook::images/blog-banner.png");
?>

<div class="blogbanner-wrapper">
	<div class="container">
		<div class="blogbanner-inner">
			<div class="blogbanner-left-content">
				<div class="header-text">Content-<span class="diff-header-text">Ready Business</span> Decks </div>
				<p>Researched by Consultants from Top-Tier Management Companies</p>				
				<div class="opetion-text">
					<div class="top-header">
						<div class="left-header">
							<a href="https://www.slideteam.net/ppt-templates/product-development-powerpoint" title="Product Development" target="_blank">Product Development</a>
						</div>
						<div class="right-header">
							<a href="https://www.slideteam.net/ppt-templates/project-management-powerpoint" title="Project Management" target="_blank">Project Management</a>
						</div>
					</div>
					<div class="bottom-header">
						<div class="left-header">
							<a href="https://www.slideteam.net/ppt-templates/business-review" title="Business Review" target="_blank">Business Review</a>
						</div>
						<div class="right-header">
							<a href="https://www.slideteam.net/ppt-templates/pitch-decks-presentations" title="Pitch Deck" target="_blank">Pitch Deck</a>
						</div>
					</div>
				</div>
				<div class="header-get-start">
					<a href="https://www.slideteam.net/ppt-templates/powerpoint-templates" title="Get Started">
					<button class="button btn" title="Get Started" type="button" id="getstartheader"><span><span>Get Started</span></span></button>
					</a>
					<!-- TrustBox widget - Drop-Down -->
					<div class="trustpilot-widget trustpilot-blog-widget" data-locale="en-US" data-template-id="5418052cfbfb950d88702476" data-businessunit-id="5c88cdf9d8c4bb0001df0960" data-style-height="30px" data-style-width="100%" data-theme="light" data-tags="slideteam">
					<a href="https://www.trustpilot.com/review/slideteam.net" target="_blank" rel="noopener" title="Trustpilot">Trustpilot</a>
					</div>
					<!-- End TrustBox widget -->
				</div>
			</div>
			<div class="blogbanner-right-content">
				<a href="https://www.slideteam.net/search/go?format=cat1&isort=globalpop&lbc=slideteam&method=and&p=Q&ts=custom&uid=114669220&w=*&af=cat1%3acompletedecks&cnt=300">
					<img src="<?php echo $this->getViewFileUrl('Tatva_Ebook::images/banner_img.png'); ?>" loading="auto" alt="Banner Image">
				</a>
			</div>
		</div>
	</div>	
</div>