<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php
	$_item = $block->getItem();
	$product = $_item->getProduct();
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
	<?php if ($product->getTypeId() != \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE): ?>
	    <a href="#"
	       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
	       class="use-ajax action action-towishlist">
	        <span><?= $block->escapeHtml(__('Move to Wishlist')) ?></span>
	    </a>
	<?php endif ?>
<?php endif ?>
