<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<tr>
   <td style="font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;padding:0;margin:0">
      <table style="border-collapse:collapse;padding:0;margin:0;width:100%;background:#e1f0f8" cellpadding="0" cellspacing="0" border="0" >
         <tbody>
            <tr>
                  <td style="font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;padding:20px 15px;margin:0;text-align:right;line-height:20px">
                     <table style="border-collapse:collapse;padding:0;margin:0;width:100%" cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tbody>
                            <tr>
                              <td colspan="3" style="padding:3px 9px;font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;margin:0" align="right"> 
                                 <table style="border-collapse:collapse;padding:0;margin:0;width:100%" cellpadding="0" cellspacing="0" border="0">
                                       <tbody>
                                       <?php foreach ($block->getTotals() as $_code => $_total): ?>
                                             <?php if ($_total->getBlockName()): ?>
                                                <?=$block->getChildHtml($_total->getBlockName(), false)?>
                                             <?php else: ?>
                                                <?php if ($_total->getStrong()): ?>
                                                   <tr>
                                                      <td colspan="3" style="padding:3px 9px;font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;margin:0" align="right"><strong><?=$block->escapeHtml($_total->getLabel())?></strong></td>
                                                      <td style="padding:3px 9px;font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;margin:0" align="right"><strong><?=/* @escapeNotVerified */$block->formatValue($_total)?></strong></td>
                                                   </tr>
                                                               
                                                <?php else: ?>
                                                   <tr>
                                                      <td colspan="3" style="padding:3px 9px;font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;margin:0" align="right"><?=$block->escapeHtml($_total->getLabel())?></td>
                                                      <td style="padding:3px 9px;font-family:Verdana,Arial;font-weight:normal;border-collapse:collapse;vertical-align:top;margin:0" align="right"><?=/* @escapeNotVerified */$block->formatValue($_total)?></td>
                                                   </tr>
                                                <?php endif?>
                                             <?php endif?>
                                          <?php endforeach?>
                                       </tbody>
                                    </table>
                                 </td>
                              </tr>
                        </tbody>
                     </table>
                  </td>
            </tr>
         </tbody>
      </table>
   </td>
</tr>