<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php 
    $contact_attribute = $block->getCustomer()->getCustomAttribute('contact_number');
    $customer_country_code = $block->getCustomer()->getCustomAttribute('customer_country_code');
    $customertype = $block->getCustomerLoginType($block->getCustomer()->getId());
    if(isset($contact_attribute))
    {
        $contact_number = $contact_attribute->getValue();
        $contacts=explode(' ',$contact_number,2);
        $telephone=(count($contacts) == 2)?$contacts[1]:$contacts[0];
    } else{
        $telephone='';
        $contact_number = '';
    }
    if(isset($customer_country_code)){
        $countryCode=$customer_country_code->getValue();
    }else{
        $countryCode=null;
    }
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="contact-fields">
            <div class="field custom-contact-detail">
                <div class="control">
                    <select id="country-isd-code" class="phonecode-dropdown custom-dropdown" name="isd-code" data-validate="{required:true}">
                        <option value="">Select Country Code</option>
                        <?php foreach ($block->getCountryData() as $value): ?>
                            <option value="<?php echo $value['isd_code'] ?>" id="<?php echo $value['country_id'] ?>"<?php if( isset($countryCode) && $value['country_id'] == $countryCode ): ?> selected="selected"<?php endif; ?>><?php echo $value['country_name'].' (+'.$value['isd_code'].')'; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div id="country-code-error" generated="true" style="color:#d24031;font-size: 13px;margin-bottom:10px;"></div>
                </div>
            </div>        
            <div class="field contact_number required">
                <label class="label" for="contact_number"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="text" name="contact_number" id="contact_number"  value="<?php echo $telephone; ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text" data-validate="{'contactNumberValidation':true}" />
                </div>
            </div>
        </div>
        <input type="hidden" name="country_id" id ="country_id" value="">
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Password')) ?></span></legend><br>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
         <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><small> << </small><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
        <div class="primary">
            <button type="submit" class="action save primary" id="final-submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        $(document).ready(function(){
            var customertype = "<?php echo $customertype; ?>";
            if (customertype == '' || customertype == null){
                $(".field.choice").css("display", "block");
                $('#change-password').prop('checked', true);
                $(".form-edit-account .fieldset.password").css("display","block");
            }
        });
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<script type="text/javascript">
require(['jquery','jquery-ui-modules/core','jquery-ui-modules/widget','jquery/validate','mage/translate'], function ($) {
    'use strict';
    $.validator.addMethod(
        "contactNumberValidation",
        function (v) {
            return $.mage.isEmptyNoTrim(v) || /^((\d+)(\-|\s){0,1})*\d+$/.test(v);
        },
        $.mage.__("Allowed digits[0-9] and -")
    );
    $("#country_id").val($("#country-isd-code").children(":selected").attr("id"));
    $("#country-isd-code").change(function() {
      var value = $(this).children(":selected").attr("id");
      $("#country_id").val(value);
    });
    $('#final-submit').click(function(){
        var phonenumber = $('#contact_number').val();
        var countrycode = $('#country-isd-code').val();
        if(phonenumber != "" && countrycode == "")
        {
            $('#country-code-error').show();
            $('#country-code-error').html('Please select your country code to add phone number.');
            $(".custom-contact-detail #dk0-combobox").css('border-color','#df280a');
            return false;
        } else{
            $(".custom-contact-detail #dk0-combobox").css('border-color','silver');
            $('#country-code-error').hide();
        }
    });
})
</script>
