<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */

?>
<div class="container forgotpwd-wrapper">
    <?= $block->getChildHtml('form_additional_info') ?>
    <form class="form password forget" action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <h4><?= $block->escapeHtml(__('Retrieve your password here')) ?></h4>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below. You will receive a link to reset your password.')) ?></div>
            <p class="required"><?= $block->escapeHtml(__('* Required Fields')) ?></p>
            <div class="field email required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}" autocapitalize="off" autocorrect="off" spellcheck="false">
                </div>
            </div>
        </fieldset>
        <div class="buttons-set">
            <?php if($block->isCustomerLogin()): ?>
            <a class="action back back-link" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><small><?= $block->escapeHtml(__('« ')) ?></small><?= $block->escapeHtml(__('Back to Login')) ?></span></a>
            <?php endif ?>
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
        </div>
    </form>
</div>