<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info">
        <?php echo $this->getChildHtml('customer.form.instruction'); ?>
        <p class="cx-or-text">- or -</p>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email Address')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}"> 
            </div>
        </div>
        <div class="customer-name-wrapper clearfix">
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        </div>
        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="customer-password-wrapper clearfix">
            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Choose Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           data-msg-validate-customer-password="Please enter 6 or more characters. Leading or trailing spaces will be ignored."
                           autocomplete="off" />
                </div>

            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" data-msg-equalTo="Please make sure your passwords match." autocomplete="off">
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
        <!--Telephone -->
        <div class="custom-optional-text-wrapper"><span class="custom-optional-text">(Optional) Please enter your phone number if you'd like us to call you to explain our products and services.</span></div>
        <div class="custom-contact-detail">
            <select id="country-isd-code" class="phonecode-dropdown custom-dropdown" name="isd-code">
                <option value="">Select Country Code</option>
                <?php foreach ($block->getCountryData() as $value): ?>
                    <option value="<?php echo $value['isd_code'] ?>" id="<?php echo $value['country_id'] ?>"><?php echo $value['country_name'].' (+'.$value['isd_code'].')'; ?></option>
                <?php endforeach; ?>
            </select>
            <div id="country-code-error" generated="true" style="color:#d24031;font-size: 13px;margin-bottom:10px;"></div>
        </div>
        <div class="field contact_number">
            <label for="contact_number" class="label">
                <span>
                    <?= $block->escapeHtml(__('Phone Number')) ?>
                </span>
            </label>
            <div class="control">
                <input type="text" name="contact_number" id="contact_number" value="" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text" data-validate="{'contactNumberValidation':true}">
            </div>
        </div>
        <input type="hidden" name="country_id" id ="country_id" value="">
        <?php  if ($this->isNewsletterEnabled()):?>
        <div class="control icheckbox-box">
            <div class="custom-newsletter-box">
                <div class="input-box"> 
                    <input type="checkbox" data-type="customCheck" name="is_subscribed" title="<?= $block->escapeHtml(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                </div>
                <span class="newsletter_register"><?= $block->escapeHtml(__("I'd like to receive email about product updates, personalized recommendations, offers, and PowerPoint and presentation tips and tricks.")) ?></span>
            </div>
        <div>
        <?php endif; ?>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" id="final-submit" title="<?= $block->escapeHtmlAttr(__('Sign Up')) ?>"><span><?= $block->escapeHtml(__('Sign Up')) ?></span></button>
            </div>
        </div>
        <p>By Pressing "Sign up" you accept our Privacy Policy</p>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend>
            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
            <?php endif ?>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $block->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" style="display:none;">
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif; ?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>


</form>
<script>
    require([
            'jquery',
            'mage/mage',
            'jquery-ui-modules/core',
            'jquery-ui-modules/widget',
            'jquery/validate',
            'mage/translate'
            ], function($){
                $.validator.addMethod(
                'validate-customer-password',function (value) {
            if(value) return true;
            else return false;
        }, $.mage.__('Please select a variant!'));

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
    dataForm.mage('validation', {
<?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
        if (element.prop('id').search('full') !== - 1) {
        var dobElement = $(element).parents('.customer-dob'),
                errorClass = error.prop('class');
        error.insertAfter(element.parent());
        dobElement.find('.validate-custom').addClass(errorClass)
                .after('<div class="' + errorClass + '"></div>');
        }
        else {
        error.insertAfter(element);
        }
        },
                ignore: ':hidden:not(' + ignore + ')'
<?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
<?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');
    });
</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
        {
        "#country": {
        "regionUpdater": {
        "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
        "regionListId": "#region_id",
        "regionInputId": "#region",
        "postcodeId": "#zip",
        "form": "#form-validate",
        "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
        "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
        "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
        }
        }
        }
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
    ".field.password": {
    "passwordStrengthIndicator": {
    "formSelector": "form.form-create-account"
    }
    }
    }
</script>
<script type="text/javascript">
require(['jquery','jquery-ui-modules/core','jquery-ui-modules/widget','jquery/validate','mage/translate'], function ($) {
    'use strict';
    $.validator.addMethod(
        "contactNumberValidation",
        function (v) {
            return $.mage.isEmptyNoTrim(v) || /^((\d+)(\-|\s){0,1})*\d+$/.test(v);
        },
        $.mage.__("Allowed digits[0-9] and -")
    );

    $.validator.addMethod(
        "SpecialCharValidation",
        function (v) {
            return $.mage.isEmptyNoTrim(v) || /^[a-zA-Z0-9_]+$/.test(v);
        },
        $.mage.__("Special characters not Allowed")
    );

    $("#country-isd-code").change(function() {
      var value = $(this).children(":selected").attr("id");
      $("#country_id").val(value);
    });

    $('#final-submit').click(function(){
        var phonenumber = $('#contact_number').val();
        var countrycode = $('#country-isd-code').val();
        if(phonenumber != "" && countrycode == "")
        {
            $('#country-code-error').show();
            $('#country-code-error').html('Please select your country code to add phone number.');
            return false;
        } else{
            $('#country-code-error').hide();
        }
    })
})
</script>
