<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="container resetpwd-wrapper">
	<div class="page-title-wrapper dashboard">
	    <div class="page-title">
	        <h3 class="base" data-ui-id="page-title-wrapper">RESET PASSWORD</h3>   
	    </div>
	</div>
	<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]])) ?>"
			method="post"
		<?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
			id="form-validate"
			class="form password reset resetpwd"
			data-mage-init='{"validation":{}}'>

		<fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
			<p class="required"><?= $block->escapeHtml(__('* Required Fields')) ?></p>
			<div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
				<label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
				<div class="control">
					<input type="password" class="input-text" name="password" id="password"
						data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
						data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
						data-validate="{required:true, 'validate-customer-password':true}"
						data-msg-validate-customer-password="Please enter 6 or more characters. Leading or trailing spaces will be ignored."
						autocomplete="off">
						<!-- <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
							<div id="password-strength-meter" class="password-strength-meter">
								<?= $block->escapeHtml(__('Password Strength')) ?>:
								<span id="password-strength-meter-label" data-role="password-strength-meter-label">
									<?= $block->escapeHtml(__('No Password')) ?>
								</span>
							</div>
						</div> -->
				</div>
			</div>
			<div class="field confirmation required">
				<label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
				<div class="control">
					<input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off" data-msg-equalTo="Please make sure your passwords match." >
				</div>
			</div>
		</fieldset>
		<div class="actions-toolbar">
			<div class="primary">
				<button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset Password')) ?></span></button>
			</div>
		</div>
	</form>
</div>