<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>

<?php if ($postFeatureList = trim($this->getPostListFeatureHtml())): 
?>
	<?php echo $postFeatureList;endif; ?>
	<?php if ($postList = trim($this->getPostListHtml())): ?>
	<?php echo $postList ?>
<?php else: ?>
	<p class="note-msg container"><?php echo __('There are no posts matching your selection.') ?>
<?php endif; ?>